In [9]:
import re
#import functions_is as fis

import numpy as np
import string

from itertools import product
from itertools import combinations

In [3]:
def listToString(list1):
    return (''.join(map(str, list1)))


NameError: name 'm_create' is not defined

In [207]:
dim = 3
l_num = 3

[0 2 3 4 5 7 6 1]
[[0 0 0 0]
 [0 0 0 1]
 [1 0 0 3]
 [0 1 0 4]
 [1 1 0 5]
 [0 0 1 6]
 [1 0 1 8]
 [0 1 1 7]
 [1 1 1 2]]


In [87]:
# 1. создать таблицу листов
# 2. на ее основе заполнить табл К
l_num = 3
K = [i for i in range(0,2**l_num)]
print(K)
res = np.zeros(l_num, dtype = int)
# b = np.array((2,2,2)).reshape(3,1)
#print("{:03b}".format(7))

for i in range(1, 2**l_num): 
    tx = "{num:0{field}b}".format(num=i,field=l_num)
    tx = tx.lstrip()
    tx = tx[::-1]
    res_t = [int(i) for i in tx]
    #res = np.vstack((res, np.array(res_t)))
    res = np.vstack((res, res_t))

print(res)
res = np.hstack((res, np.array(K).reshape(2**l_num,1)))
res[:, 0], res[:, 2] = res[:, 2], res[:, 0].copy()
print(res)

# %timeit my_array[:, 0], my_array[:, 1] = my_array[:, 1], my_array[:, 0].copy()
# The slowest run took 15.05 times longer than the fastest. This could mean that an intermediate result is being cached 
# 1000000 loops, best of 3: 1.72 µs per loop
# The advanced slicing times are:

# %timeit my_array[:,[0, 1]] = my_array[:,[1, 0]]
# The slowest run took 7.38 times longer than the fastest. This could mean that an intermediate result is being cached 
# 100000 loops, best of 3: 6.9 µs per loop

ind1 = np.lexsort((res[:,0], res[:,1], res[:,2]))
print(ind1)
b = np.zeros(4, dtype = int)

for i in ind1:
    b = np.vstack((b, res[i,:]))
b = b[1:b.shape[0],:]
#del first row
print(b)

[0, 1, 2, 3, 4, 5, 6, 7]
[[0 0 0]
 [1 0 0]
 [0 1 0]
 [1 1 0]
 [0 0 1]
 [1 0 1]
 [0 1 1]
 [1 1 1]]
[[0 0 0 0]
 [0 0 1 1]
 [0 1 0 2]
 [0 1 1 3]
 [1 0 0 4]
 [1 0 1 5]
 [1 1 0 6]
 [1 1 1 7]]
[0 4 2 6 1 5 3 7]
[[0 0 0 0]
 [1 0 0 4]
 [0 1 0 2]
 [1 1 0 6]
 [0 0 1 1]
 [1 0 1 5]
 [0 1 1 3]
 [1 1 1 7]]


In [99]:
# upper layer iteration
lnum = 3
dim = 2
#K = [i for i in range(0,2**l_num)]
K = [i%2 for i in range(0,2**l_num)]
print(K)
lenumeration = [i for i in range(1,lnum+1)] 
print(lenumeration)
res = np.zeros(lnum, dtype = int)
# b = np.array((2,2,2)).reshape(3,1)
#print("{:03b}".format(7))

for i in range(1, 2**l_num): 
    tx = "{num:0{field}b}".format(num=i,field=l_num)
    tx = tx.lstrip()
    tx = tx[::-1]
    res_t = [int(i) for i in tx]
    #res = np.vstack((res, np.array(res_t)))
    res = np.vstack((res, res_t))

#print(res)
res = np.hstack((res, np.array(K).reshape(2**l_num,1)))

# собрать новый массив из двух частей: 1. столблцы группы неч. 2. столбцы дополнения
# эти два массива объединить в один

#lnumingroup = 2 #len(lst[j])
lcombinations = list(combinations(range(1, lnum+1), lnumingroup))
print(lcombinations)

for j in range(0, len(lcombinations)):
    # fill res1 (1. столблцы группы неч.)
    print(j)
    res1 = np.array([res[:, lcombinations[j][0]-1]])
    # ini np.array
    for n in range(1, len(lcombinations[j])):
        res1 = np.vstack((res1, res[:, lcombinations[j][n]-1]))
    #print(res1)
    
    reminder = list(set(lenumeration)-set(lcombinations[j])) 
    res2 = np.array([res[:, reminder[0]-1]])
    for n in range(1, lnum-len(lcombinations[j])):
        res2 = np.vstack((res2, res[:, reminder[n]-1]))
    #print(res2)
    res3 = np.vstack((res1, res2))
    res3 = np.vstack((res3, res[:,res.shape[1]-1])).T
    print(res3)
    
    ind1 = np.lexsort((res3[:,0], res3[:,1], res3[:,2]))
    print(ind1)
    
    b = np.zeros(lnum+1, dtype = int)
    # для составления таблицы К по групам мне нужет только последний столбец
    # или даже только ind1 - можно сократить этот код
    for i in ind1:
        b = np.vstack((b, res3[i,:]))
    b = b[1:b.shape[0],:]
    #del first row
    print(b)
    
    tbl_k = np.array(b[:,b.shape[1]-1]).reshape(dim**len(lcombinations[j]),dim**len(reminder))
    #K = K.T
    print(tbl_k)
    # можно реализовать через lcombinations = list(combinations(range(1, lnum+1), lnumingroup))
    for q in range(0,tbl_k.shape[0]-1):
        #print("q",q)
        for w in range(q+1,tbl_k.shape[0]):
            #print("w",w)
            if (tbl_k[q,:] == tbl_k[w,:]).all(): 
                print("found group for merge")
    # найденные группы склеивай и выходи через брейк к следующему q


names = []
for i in range(0,len(lst)):
    names.append(listToString(lst[i]))
# columns for perm in list table
print(names)

#сделай  pd.data.frame со столбцами с этими именами и размещай в них результаты
#print(res)

[0, 1, 0, 1, 0, 1, 0, 1]
[1, 2, 3]
[(1, 2), (1, 3), (2, 3)]
0
[[0 0 0 0]
 [1 0 0 1]
 [0 1 0 0]
 [1 1 0 1]
 [0 0 1 0]
 [1 0 1 1]
 [0 1 1 0]
 [1 1 1 1]]
[0 1 2 3 4 5 6 7]
[[0 0 0 0]
 [1 0 0 1]
 [0 1 0 0]
 [1 1 0 1]
 [0 0 1 0]
 [1 0 1 1]
 [0 1 1 0]
 [1 1 1 1]]
[[0 1]
 [0 1]
 [0 1]
 [0 1]]
found group for merge
found group for merge
found group for merge
found group for merge
found group for merge
found group for merge
1
[[0 0 0 0]
 [1 0 0 1]
 [0 0 1 0]
 [1 0 1 1]
 [0 1 0 0]
 [1 1 0 1]
 [0 1 1 0]
 [1 1 1 1]]
[0 1 4 5 2 3 6 7]
[[0 0 0 0]
 [1 0 0 1]
 [0 1 0 0]
 [1 1 0 1]
 [0 0 1 0]
 [1 0 1 1]
 [0 1 1 0]
 [1 1 1 1]]
[[0 1]
 [0 1]
 [0 1]
 [0 1]]
found group for merge
found group for merge
found group for merge
found group for merge
found group for merge
found group for merge
2
[[0 0 0 0]
 [0 0 1 1]
 [1 0 0 0]
 [1 0 1 1]
 [0 1 0 0]
 [0 1 1 1]
 [1 1 0 0]
 [1 1 1 1]]
[0 2 4 6 1 3 5 7]
[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [1 0 1 1]
 [0 1 1 1]
 [1 1 1 1]]
[[0 0]
 [0 0]
 [1 1]
 [1

In [65]:
from timeit import default_timer as timer

print(set(lst[1]))

list1 = list(lst[1])
print(list1)
list2 = [i for i in range(1,lnum+1)] 
print(list2)
print(set(list1))
t = timer()
set(list2) - set(list1)
elapsed = timer() - t
print(elapsed)
list3=list(set(list2)-set(list1))  
print(list3 )
t = timer()
lst3 = [i for i in list2 if i not in list1]
elapsed = timer() - t
print(elapsed)

print(lst3)


{1, 3}
[1, 3]
[1, 2, 3]
{1, 3}
3.169999945384916e-05
[2]
4.189999890513718e-05
[2]


In [9]:
#K = np.zeros((4,4), dtype = int)
K = np.empty((4,4), dtype = int)
K
K = np.array(b[:,3]).reshape(4,2)
K = K.T

print((K[0,:] == K[1,:]).all())
# для следующей итерации замени столбец К на новый, чтобы не копировать таблицу

False


In [10]:
# another way gen table of leaves
# chars = '0'
# print(list(product(chars, repeat=4)))
chars = '01'
print(list(product(chars, repeat=3)))
t = np.array(list(product(chars, repeat=3)))
t

[('0', '0', '0'), ('0', '0', '1'), ('0', '1', '0'), ('0', '1', '1'), ('1', '0', '0'), ('1', '0', '1'), ('1', '1', '0'), ('1', '1', '1')]


array([['0', '0', '0'],
       ['0', '0', '1'],
       ['0', '1', '0'],
       ['0', '1', '1'],
       ['1', '0', '0'],
       ['1', '0', '1'],
       ['1', '1', '0'],
       ['1', '1', '1']], dtype='<U1')