In [2]:
'''Analisis of equivalency groups
on conflict basis'''
# take care about param types
import re
#import functions_is as fis

import numpy as np
import pandas as pd
import string # for int2base

from itertools import product
from itertools import combinations
import itertools
import timeit
import datetime
date = datetime.datetime.today()
# https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior
print('time', date.strftime("%H:%M"))
import copy

time 22:01


In [3]:
def listToString(list1):
    return (''.join(map(str, list1)))
def listToString_cmm(list1):
    return (','+','.join(map(str, list1))+',')

def list_getsome(vec, positions):
    list_n = []
    for y in positions:
        list_n.append(vec[y])
    #print("lnf", list_n)
    return(list_n)

# convert into different bases
dim = 4
np.base_repr(11111100, base=dim)
int('3333333333', base=dim)
int('33333333', base=dim)

def diversity_num(vec, dim):
    dvst = 0
    for i in range(0, dim):
        for j in range(0, len(vec)):
            if vec[j] == i:
                dvst += 1
                break
    return dvst
vec1 = [np.nan, 1,np.nan, np.nan, 1, 2, np.nan, np.nan, np.nan, np.nan, 2, np.nan]
print(diversity_num(vec1, 3))
def diversity_vec(vec, dim):
    dvst = []
    for i in range(0, dim):
        for j in range(0, len(vec)):
            if vec[j] == i:
                dvst.append(i)
                break
    return dvst
print(diversity_vec(vec1, 3))

2
[1, 2]


In [40]:
# no need to gen table of examples
# just gen table of nans of size corresponding to group
# and fill it by data values
#dim = 4
#load incomplete data
#data = pd.read_csv('feeley2012_cl_d4.csv', sep=',')
data = pd.read_csv('210409_id_arctic_l5_datatable.csv', sep=',')
#print(data)
# data should contain only leaves and K columns, it is format
#data.duplicated()
lnum = data.shape[1]-1
print("lnum = ", lnum)
data = np.array(data.iloc[:,0:lnum+1])
print("data: \n" ,data)
print("max: ", data.max())
print("min: ", data.min())
dim = 1+data.max()-data.min()
print("dim = ", (data.max()-data.min())+1)
print("K: " ,data[:,lnum-1])

# all posible values of group numbers
lenumeration = [i for i in range(0,lnum)] 

cnt = 0
for l_incomb in range(3,4):
    lcombinations = list(combinations(range(0, lnum), l_incomb))
    print("lcombinations", lcombinations)
    #print(tbl_k)
    # form table K for every group
    for j in range(4, 5):
        print("j: ", j)
        print(lcombinations[j])
        tbl_k = np.empty((dim**l_incomb,dim**(lnum-l_incomb)))
        tbl_k.fill(np.nan)
        colfilled = []
        seen = set()
        # fill table K from data string by sting (x)
        for x in range(0,len(data)):
            #print(data[x,lcombinations[j]])
            # get coordinate in nondecimal representation of string
            data[x,lcombinations[j]]
            # get coordinate in nondecimal representation of column
            reminder = list(set(lenumeration)-set(lcombinations[j])) 
            data[x,reminder]
            #print(data[x,lcombinations[j]])
            #print(data[x,reminder])
            # need to place F value in Ktable to selected coordinates
            c1 = "".join([str(xx) for xx in data[x,lcombinations[j]]])
            c2 = "".join([str(xx) for xx in data[x,reminder]])
            c2_t = int(c2[::-1], base = dim)
            #print(int(c1[::-1], base = dim)," ", c2_t)
            #print(int(c2[::-1], base = dim))
            tbl_k[int(c1[::-1], base = dim), c2_t] = data[x,lnum]
            # попутно можно записать все столбцы в которых есть значения, соотв. другие м.б. удал.
            if c2_t not in seen:
                seen.add(c2_t)
                colfilled.append(c2_t)
        #print("uniq col ", len(colfilled))
        #print(colfilled)  
        tbl_k_s = tbl_k[:,colfilled]
        numbers = [int(i) for i in range(0,len(tbl_k_s))]
        tbl_k_s = np.hstack((np.array(numbers).reshape(len(tbl_k_s),1), tbl_k_s))
        print(tbl_k_s)#[0:30,:]
        # del nan rows
        rows_nan = np.all(np.isnan(tbl_k_s), axis = (1))
        print(~rows_nan)
        tbl_k_s = tbl_k_s[~rows_nan,:]
        print(tbl_k_s)

lnum =  5
data: 
 [[2 1 1 2 0 2]
 [1 0 0 1 0 1]
 [1 1 2 0 2 2]
 [2 1 2 2 1 2]
 [1 1 0 1 1 2]
 [1 1 1 1 1 2]
 [2 2 2 1 1 2]
 [2 2 2 2 2 2]
 [1 2 1 2 1 1]
 [1 0 1 1 0 1]
 [0 1 1 2 1 1]
 [2 2 1 2 1 2]
 [2 0 1 1 1 2]
 [2 2 1 1 0 2]
 [2 2 2 2 1 2]
 [1 1 2 1 1 2]
 [0 1 1 1 1 2]
 [0 0 0 1 0 1]
 [2 1 1 0 0 1]
 [0 1 0 1 0 2]
 [2 0 0 2 1 2]
 [2 1 1 1 1 2]
 [1 1 2 0 1 1]
 [2 0 0 0 0 1]
 [1 1 0 2 2 2]
 [1 0 0 1 1 1]
 [1 0 1 2 0 1]
 [1 1 1 2 1 1]
 [0 0 1 0 0 0]
 [1 0 0 0 0 1]
 [1 1 1 0 1 1]]
max:  2
min:  0
dim =  3
K:  [0 0 2 1 1 1 1 2 1 0 1 1 1 0 1 1 1 0 0 0 1 1 1 0 2 1 0 1 0 0 1]
lcombinations [(0, 1, 2), (0, 1, 3), (0, 1, 4), (0, 2, 3), (0, 2, 4), (0, 3, 4), (1, 2, 3), (1, 2, 4), (1, 3, 4), (2, 3, 4)]
j:  4
(0, 2, 4)
[[ 0. nan  1. nan  2. nan nan nan nan]
 [ 1. nan  1. nan nan nan nan nan  1.]
 [ 2. nan nan nan nan nan nan nan  1.]
 [ 3. nan nan nan nan nan nan nan  0.]
 [ 4. nan  1. nan nan nan nan  1. nan]
 [ 5.  2. nan  1. nan  2. nan nan nan]
 [ 6. nan nan nan nan nan nan nan nan]
 [ 7. nan

In [67]:
data = pd.read_csv('02_arctic_5x3_201223_data.csv', sep=',')
#print(data)
# data should contain only leaves and K columns, it is format
data.iloc[:,0:6].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [79]:
# check for nans

mysetup = '''
import numpy as np; 
x = np.random.rand(100000)
#x[50000] = np.nan
'''
print (timeit.timeit(setup = mysetup, stmt = "~np.isnan(np.min(x))",
                     number = 1000)) 
print (timeit.timeit(setup = mysetup, stmt = "np.isnan(np.sum(x))",
                     number = 1000)) 
print (timeit.timeit(setup = mysetup, stmt = "np.isnan(x).any()",
                     number = 1000)) 
x = np.random.rand(100000)
x
np.isnan(np.min(x))
#x[50000] = np.nan
np.isnan(np.min(x))
np.isnan(np.sum(x))
~np.isnan(x).any()

0.017413499999747728
0.03204310000000987
0.017648499999268097


True

In [32]:
# upper layer iteration
# test if the set of examples can be realised 
# with incopmlete techniqe

# могу удалять строки с нан, т.к. с т.з. ГЭ они не работают
# приведи тип переменных в массиве к инт

# len_combinations = 0
# for i in range(2,lnum):
#     lcombinations = list(combinations(range(0, lnum), i))
#     len_combinations += len(lcombinations)
# #numofisg = np.zeros(3, dtype='S20, int')
# dfnumofisg = pd.DataFrame(
#     {
#         "name": np.array(len_combinations*2, dtype="str"),
#         "val": np.empty(len_combinations*2, dtype="int32"),
#     }
# )
# cnt = 0
# for i in range(2,lnum):
#     lcombinations = list(combinations(range(0, lnum), i))
#     # posible combinatins of groups
#     #print(lcombinations)
#     for i in range(len(lcombinations)):
#         #print("lcombinations[i] ", lcombinations[i])
#         #numofisg[cnt,0] = int(''.join(map(str, lcombinations[i])))
#         dfnumofisg.iat[cnt,0] = ''.join(map(str, lcombinations[i]))
#         dfnumofisg.iat[cnt,1] = 0
#         #print("dfnumofisg[i] ", dfnumofisg.iloc[cnt,:])
#         cnt += 1

#dim = 4
#load incomplete data
#data = pd.read_csv('feeley2012_cl_d4.csv', sep=',')
#data = pd.read_csv('210409_id_arctic_l5_datatable.csv', sep=',')
data = pd.read_csv('02_arctic_5x3_201223_data.csv', sep=';')
#print(data)
# data should contain only leaves and K columns, it is format
#data.duplicated()
lnum = data.shape[1]-1
print("lnum = ", lnum)
data = np.array(data.iloc[:,0:lnum+1])
#print("data: \n" ,data)
print("max: ", data.max())
print("min: ", data.min())
dim = 1+data.max()-data.min()
print("dim = ", (data.max()-data.min())+1)
print("K: " ,data[:,lnum-1])

# all posible values of group numbers
lenumeration = [i for i in range(0,lnum)] 

cnt = 0
for l_incomb in range(2,3):
    lcombinations = list(combinations(range(0, lnum), l_incomb))
    print("lcombinations", lcombinations)
    #print(tbl_k)
    # form table K for every group
    for j in range(0, 1):
        print("j: ", j)
        print(lcombinations[j])
        tbl_k = np.empty((dim**l_incomb,dim**(lnum-l_incomb)))
        tbl_k.fill(np.nan)
        colfilled = []
        seen = set()
        # fill table K from data string by sting (x)
        for x in range(0,len(data)):
            #print(data[x,lcombinations[j]])
            # get coordinate in nondecimal representation of string
            data[x,lcombinations[j]]
            # get coordinate in nondecimal representation of column
            reminder = list(set(lenumeration)-set(lcombinations[j])) 
            data[x,reminder]
            # need to place F value in Ktable to selected coordinates
            c1 = "".join([str(xx) for xx in data[x,lcombinations[j]]])
            c2 = "".join([str(xx) for xx in data[x,reminder]])
            c2_t = int(c2[::-1], base = dim)
            #print(int(c1[::-1], base = dim)," ", c2_t)
            #print(int(c2[::-1], base = dim))
            tbl_k[int(c1[::-1], base = dim), c2_t] = data[x,lnum]
            # попутно можно записать все столбцы в которых есть значения, соотв. другие м.б. удал.
            if c2_t not in seen:
                seen.add(c2_t)
                colfilled.append(c2_t)
        #print("uniq col ", len(colfilled))
        #print(colfilled)  
        tbl_k_s = tbl_k[:,colfilled]
        #print(tbl_k_s)#[0:30,:]
        # del nan rows
        rows_nan = np.all(np.isnan(tbl_k_s), axis = (1))
        print(~rows_nan)
        tbl_k_s = tbl_k_s[~rows_nan,:]
        numbers = [int(i) for i in range(0,len(tbl_k_s))]
        numbers_col = [int(i) for i in range(-1,tbl_k_s.shape[1])]
        temp_k = np.hstack((np.array(numbers).reshape(len(tbl_k_s),1), tbl_k_s))
        #print(np.array(numbers_col).reshape(1,temp_k.shape[1]))
        temp_k = np.vstack((np.array(numbers_col).reshape(1,temp_k.shape[1]), temp_k))
        #print(tbl_k_s)
        print(temp_k)
        # for now it is necessary to analyze whether the given alphabet is enough
        # second way of analisis
        list_ind = [[i for i in range(tbl_k_s.shape[0])]]
        # range of strings

        for r in range(tbl_k_s.shape[1]):
            # select a column, from back because extend used further
            print(" col", r)
            if diversity_num(tbl_k_s[:,r], dim) > 1:
                    # if there is conflict of type 1 = more than 1 different digit in col
                #checklist = tbl_k_s[:,r]
                checklist = copy.deepcopy(tbl_k_s[:,r])
                checklist_pos = 0
                for z in range(len(list_ind)-1,-1,-1): 
                    # select a range in list_ind
                    # rev list - это связано с тем что del удаляет с конца
                    #print("list_ind", list_ind)
                    #print("  z, list_ind[z]", z, list_ind[z])
                    ind_t = []
                    flag_del_inigroup = 0
                    for w in range(dim):
                        #print("   w= ", w)
                        # search for every simbol in alphabet                       
                        range_in_range = np.where(tbl_k_s[list_ind[z],r] == w)[0].tolist()
                        #print("range_in_range", range_in_range)
                        if r > 0 and len(range_in_range):
                            plus_na = np.argwhere(np.isnan(tbl_k_s[list_ind[z],r]))
                            plus_na = list(itertools.chain(*plus_na))
                            range_in_range = list(itertools.chain(*[range_in_range, plus_na]))
                        if len(range_in_range):
                            range_in_range = list_getsome(list_ind[z], range_in_range)
                            print("checklist 1: ", checklist)
                            checklist[range_in_range] = np.nan
                            print("checklist 2: ", checklist)
                            print("nums and nans in range: ", range_in_range)
                            ind_t.append(range_in_range)        
                            flag_del_inigroup = 1

                    if flag_del_inigroup:
                        del list_ind[z]
                        flag_del_inigroup = 0
                    # sort list for further includes and dubles checking
                    for c in range(len(ind_t)):
                        ind_t[c].sort()
                    list_ind.extend(ind_t)
                if ~np.isnan(checklist).all():
                    # test if there are not nans
                    checklist_pos = np.argwhere(~np.isnan(checklist))#[0].tolist()
                    checklist_pos = list(itertools.chain(*checklist_pos))
                    print("checklist 3: ", checklist_pos)
                    # need to insert on del place, bacause of for indexing

                print("list_ind after clearning ", list_ind)
                # seek for opportunity to expand eqg by new digits
                for zz in range(len(list_ind)):
                    ind_tt = list_ind[zz]
                    print("lst", ind_tt)
                    print("tbl on ind ", tbl_k_s[ind_tt,r])
                    #print("tbl_full ",tbl_k_s[[[i for i in range(tbl_k_s.shape[0])]],r])
                    if ~np.isnan(tbl_k_s[ind_tt,r]).all() and ~np.isnan(checklist).all():
                        # if it was any digits that groups contained, then try to merge with
                        # берем доступные числа из групп столбца и расширяем группы по ним
                        ldiv = diversity_vec(tbl_k_s[ind_tt,r], dim)
                        for i in ldiv:
                            print("checklist[checklist_pos]", checklist[checklist_pos])
                            cnt_j = 0 
                            for j in checklist[checklist_pos]:
                                if j == i:
                                    #print("checklist 3: ", checklist_pos)
                                    list_ind[zz].append(checklist_pos[cnt_j])
                                    print("list_ind new",list_ind)
                                    checklist[checklist_pos[cnt_j]] = np.nan
                                    print("checklist[checklist_pos[cnt_j]]",checklist[checklist_pos[cnt_j]])
                                cnt_j += 1
                #else # если в ГЭ нет номера из checklist, то добваить группу
                # проверить остались ли свободные числа in checklist
                #print("checklist 4 ", checklist[list(itertools.chain(*list_ind))])
                if ~np.isnan(checklist).all():
                    print("checklist 4 new group from", checklist)
                    # для каждого отдельного номинала своя группа
                    ldiv2 = diversity_vec(checklist, dim)
                    for i in ldiv2:
                        range_in_range2 = np.where(checklist == i)[0].tolist()
                        print("range_in_range2", range_in_range2)
                        #list_ind.extend(range_in_range2)
                        list_ind.append(range_in_range2)
                        print("list_ind new extended", [list_ind])
        print("res on iteration ", len(list_ind))


lnum =  5
max:  2
min:  0
dim =  3
K:  [0 2 1 1 1 1 2 1 0 1 1 1 0 1 1 1 0 0 0 1 1 1 0 2 1 0 1 0 0 1]
lcombinations [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]
j:  0
(0, 1)
[ True  True  True  True  True  True False  True  True]
[[-1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
 [ 0.  1. nan nan nan nan nan nan nan nan  0. nan nan nan nan nan nan]
 [ 1.  1. nan nan  1. nan nan nan nan  1. nan nan nan  1. nan  1. nan]
 [ 2. nan nan nan nan  2. nan nan nan nan nan  2. nan  1. nan nan nan]
 [ 3.  2. nan nan nan  2. nan nan  1. nan nan nan nan nan nan nan nan]
 [ 4. nan  2. nan  2.  2.  2. nan  1. nan nan nan  1. nan  2. nan  1.]
 [ 5. nan nan  2. nan  2. nan nan nan nan  1. nan nan nan nan nan nan]
 [ 6. nan nan nan nan nan nan nan  1. nan nan nan nan nan nan nan nan]
 [ 7. nan nan  2. nan nan  2.  2.  2.  2. nan nan nan nan nan nan nan]]
 col 0
checklist 1:  [ 1.  1. nan  2. nan nan nan nan]
checklist 2:  [nan nan nan  2. nan nan n

In [40]:
a = np.zeros(5, dtype='|S10, int')
a[0][0] = "12345"
a[0][1] = 2
a

array([(b'12345', 2), (b'', 0), (b'', 0), (b'', 0), (b'', 0)],
      dtype=[('f0', 'S10'), ('f1', '<i4')])

In [65]:
df2 = pd.DataFrame(
        {
            "D": np.array(4, dtype="int32"),
            "E": np.empty(4, dtype="str"),
        }
   )
df2.iat[0,1] = "w"
df2

D  E
0  4  w
1  4   
2  4   
3  4

In [12]:
len_combinations = 0
# number of posible list combinations
for i in range(2,lnum):
    lcombinations = list(combinations(range(1, lnum+1), i))
    len_combinations += len(lcombinations)

    
numofisg = np.zeros(len_combinations*2, dtype = int).reshape(len_combinations,2)
# for i in range(len(lcombinations)):
#     numofisg[i,0] = int(''.join(map(str, lcombinations[i])))
numofisg

cnt = 0
for i in range(2,lnum):
    lcombinations = list(combinations(range(1, lnum+1), i))
    # posible combinatins of groups
    print("i \n", i)
    print(lcombinations)
    for i in range(len(lcombinations)):
        numofisg[cnt,0] = int(''.join(map(str, lcombinations[i])))
        cnt += 1
numofisg


i 
  2
[(1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (6, 7), (6, 8), (6, 9), (6, 10), (7, 8), (7, 9), (7, 10), (8, 9), (8, 10), (9, 10)]
i 
  3
[(1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 2, 6), (1, 2, 7), (1, 2, 8), (1, 2, 9), (1, 2, 10), (1, 3, 4), (1, 3, 5), (1, 3, 6), (1, 3, 7), (1, 3, 8), (1, 3, 9), (1, 3, 10), (1, 4, 5), (1, 4, 6), (1, 4, 7), (1, 4, 8), (1, 4, 9), (1, 4, 10), (1, 5, 6), (1, 5, 7), (1, 5, 8), (1, 5, 9), (1, 5, 10), (1, 6, 7), (1, 6, 8), (1, 6, 9), (1, 6, 10), (1, 7, 8), (1, 7, 9), (1, 7, 10), (1, 8, 9), (1, 8, 10), (1, 9, 10), (2, 3, 4), (2, 3, 5), (2, 3, 6), (2, 3, 7), (2, 3, 8), (2, 3, 9), (2, 3, 10), (2, 4, 5), (2, 4, 6), (2, 4, 7), (2, 4, 8), (2, 4, 9), (2, 4, 10), (2, 5, 6), (2, 5, 7), (2, 5, 8), (2, 5, 9), (2, 5, 10), (2, 6, 7),

OverflowError: Python int too large to convert to C long

In [31]:
# test block
# incomplete eq groups with nan

dim = 2
#tbl_k = np.array([[1, 0], [1, 0], [0, 1], [0, 1]])
#tbl_k = np.array([[0, 1], [0, 1], [1, 0], [1, 0]])
#tbl_k = np.array([[0, 1, np.nan], [0, 0, np.nan], [0, 0, 0], [1, 1, 1], [np.nan, 0, 0], [np.nan, np.nan, np.nan]])
tbl_k = np.array([[1, np.nan, 0], [1, 1, 1], [np.nan, np.nan, 1], [np.nan, 0, 0], [0, np.nan, 0]])
#tbl_k = np.array([[1, np.nan, 0], [1, np.nan, 1], [np.nan, np.nan, 1], [np.nan, 0, 0], [0, np.nan, 0]])

# create table K from list combinations table and K
#K = K.T
print("tbl_k \n", tbl_k)
# можно реализовать через lcombinations = list(combinations(range(1, lnum+1), lnumingroup))

# for now it is necessary to analyze whether the given alphabet is enough
# second way of analisis
list_ind = [[i for i in range(tbl_k.shape[0])]]
# range of strings

for r in range(tbl_k.shape[1]):
    # select a column, from back because extend used further
    print(" col", r)

    for z in range(len(list_ind)-1,-1,-1): 
        # select a range in list_ind
        # rev list - это связано с тем что del удаляет с конца
        print("  z, list_ind[z]", z, list_ind[z])
        if len(list_ind) > 1 and len(list_ind[z]) == 1: continue
            # whant to reduce consideration of one term elements of list_ind
        else:
            ind_t = []
            #print("list_ind", list_ind)
            # find nans in list_ind[z]
            plus_na = np.argwhere(np.isnan(tbl_k[list_ind[z],r]))
            plus_na = list(itertools.chain(*plus_na))
            plus_na = list_getsome(list_ind[z], plus_na)
            print("   nan", plus_na)
            if len(plus_na) == len(list_ind[z]): continue
            for w in range(dim):
                print("   w", w)
                # search for every simbol in alphabet
                # need to sort list_ind[z] for correct return from np.where
                #list_ind[z].sort()
                #print("   list_ind[z] sorted", list_ind[z])
                #if np.where(tbl_k[list_ind[z],r] == w)[0].tolist():                                                                           
                range_in_range = np.where(tbl_k[list_ind[z],r] == w)[0].tolist()
                if len(range_in_range):
                    # Если группа для данного значения не пуста приклеиваем к ней нан. 210514 думаю это не верно, нужно сохранять групу и клеить к ней нан
                    # нельзя склеивать range_in_range и plus_na ,tp list_getsome() 
                    # - первое указывает на число в list_ind[z] второе в tbl_k
                    range_in_range = list_getsome(list_ind[z], range_in_range)
                    print("    range", range_in_range)
                    #print("    itertools.chain", list(itertools.chain(*[range_in_range, plus_na])))
                    ind_t.append(list(itertools.chain(*[range_in_range, plus_na])))
                    # no need to use list_getsome() after itertools.chain(), cause ic alredy 
                    # contain values from table
                    # another flatter flat_list = [item for sublist in t for item in sublist]
                    # another - use .extend()
                    #print('    ind_t', ind_t)
                    #ind_t.append(np.where(tbl_k[:,r] == w)[0].tolist())
                    #print("in ", list_getsome(list_ind[z],
                                          #np.where(tbl_k[list_ind[z],r] == w)[0].tolist()))
                    # may be reduced; if all values found
                    #print("found group for merge")
                    #print("in", w, ind_t)            
            del list_ind[z]
            # sort list for further includes and dubles checking
            for c in range(len(ind_t)):
                ind_t[c].sort()
            print("ind_t", ind_t)
            list_ind.extend(ind_t)
            print("  list_ind after all alfabet ",list_ind)
            #list_ind.insert(z, ind_t)
            # need to insert on del place, bacause of for indexing
    # Если в данном столбце есть нан, то нужно в итоговом list_ind проверить наличие
    # вложений и дублей. Т.е. избыточность проверяется для всего столбца
    # учти изменение таблицы в процессе
    q = 0
    while q <= len(list_ind)-2:
        u = q + 1
        while u <= len(list_ind)-1:
            #if q == u: break
                # в результате удаления предпоследней ячейки, может получиться так что 
                # последняя сравнивается сама с собой и удаляется, что недопустимо - break
            if len(str(list_ind[q])) > len(str(list_ind[u])):
                string = list_ind[q]
                patter = list_ind[u]
            else:
                string = list_ind[u]
                patter = list_ind[q]    
            result = re.search(listToString_cmm(patter), listToString_cmm(string))
            if result:
                print(result[0])
                if len(str(list_ind[q])) > len(str(list_ind[u])):
                    del list_ind[u]
                    u = u - 1 
                else:
                    del list_ind[q]
                    #break
                    # удалили расматриваемый член. переходим к следующему, но с 
                    # "начала" списка (u = q)
                    u = q 
            u += 1
        q += 1
    print("list_ind after clearning ", list_ind)
# для восстановления дерева, нужно добавить очистку от противоречий в группах

# 210514 
# 1) err: alg found "9, 0, 3, 4, 5, 6" in "49, 0, 3, 4, 5, 6"
# 2) пропадает группа с числом из первого столбца, если его нет в следующем.
# например изначально был ноль, но в следующем столбце произошло деление на 1 и 2
# а о том что был 0 упоминание пропало. М.б. так и надо?


tbl_k 
 [[ 1. nan  0.]
 [ 1.  1.  1.]
 [nan nan  1.]
 [nan  0.  0.]
 [ 0. nan  0.]]
 col 0
  z, list_ind[z] 0 [0, 1, 2, 3, 4]
   nan [2, 3]
   w 0
    range [4]
   w 1
    range [0, 1]
ind_t [[2, 3, 4], [0, 1, 2, 3]]
  list_ind after all alfabet  [[2, 3, 4], [0, 1, 2, 3]]
list_ind after clearning  [[2, 3, 4], [0, 1, 2, 3]]
 col 1
  z, list_ind[z] 1 [0, 1, 2, 3]
   nan [0, 2]
   w 0
    range [3]
   w 1
    range [1]
ind_t [[0, 2, 3], [0, 1, 2]]
  list_ind after all alfabet  [[2, 3, 4], [0, 2, 3], [0, 1, 2]]
  z, list_ind[z] 0 [2, 3, 4]
   nan [2, 4]
   w 0
    range [3]
   w 1
ind_t [[2, 3, 4]]
  list_ind after all alfabet  [[0, 2, 3], [0, 1, 2], [2, 3, 4]]
list_ind after clearning  [[0, 2, 3], [0, 1, 2], [2, 3, 4]]
 col 2
  z, list_ind[z] 2 [2, 3, 4]
   nan []
   w 0
    range [3, 4]
   w 1
    range [2]
ind_t [[3, 4], [2]]
  list_ind after all alfabet  [[0, 2, 3], [0, 1, 2], [3, 4], [2]]
  z, list_ind[z] 1 [0, 1, 2]
   nan []
   w 0
    range [0]
   w 1
    range [1, 2]
ind_t [[0], [

In [65]:
# test block
# search for duplicates and includes in list of groups
# need to analize by items
# do not del items like [5, 82], [28, 82]

#list_ind = [[12345], [23], [5], [123456], [32], [32]]
#list_ind = [[1], [12345], [67], [5], [123456], [32], [67], [32]]
#list_ind = [[1], [12, 3, 45], [45, 12, 3], [12, 3, 456], [1], [67], [5], [1, 123, 45], [5, 82], [28, 82], [28, 82], [82, 28]]
# не клеит если стоит цифра разделитель в большем множестве:
list_ind =  [[0, 3, 5, 7], [0, 2, 5, 6, 7], [0, 3, 5, 6, 7], [0, 1, 3, 6, 7], [0, 1, 2, 6, 7], [0, 1, 4, 7], [0, 1, 3, 7]]
string = list_ind[1]
#print(listToString(string))

for c in range(len(list_ind)):
                list_ind[c].sort()

# for q in range(len(list_ind)): 
#         for w in range(q+1,len(list_ind)): 
q = 0
while q <= len(list_ind)-2:
    u = q + 1
    while u <= len(list_ind)-1:
#         print("  list", list_ind)
#         print("  l", len(list_ind))
#         print("  q", q)
#         print("  u", u)
        #if q == u: break
            # в результате удаления предпоследней ячейки, может получиться так что 
            # последняя сравнивается сама с собой и удаляется, что недопустимо - break
        if len(str(list_ind[q])) > len(str(list_ind[u])):
            string = list_ind[q]
            patter = list_ind[u]
        else:
            string = list_ind[u]
            patter = list_ind[q]    
#         print("new pair")
#         print(listToString_cmm(patter))
#         print(listToString_cmm(string))
        result = re.search(listToString_cmm(patter), listToString_cmm(string))
        if result:
            print(result[0])
            if len(str(list_ind[q])) > len(str(list_ind[u])):
                del list_ind[u]
                u = u - 1 
            else:
                del list_ind[q]
                #break
                # удалили расматриваемый член. переходим к следующему, но с 
                # "начала" списка (u = q)
                u = q 
        u += 1
    q += 1
    
print(list_ind)

[[0, 3, 5, 7], [0, 2, 5, 6, 7], [0, 3, 5, 6, 7], [0, 1, 3, 6, 7], [0, 1, 2, 6, 7], [0, 1, 4, 7], [0, 1, 3, 7]]


In [25]:
def listToString_cmm(list1):
    return (','+','.join(map(str, list1))+',')
list_ind = [[1], [12, 3, 45], [67], [5], [123, 45, 6], [82], [28]]
listToString_cmm(list_ind[1])
#set(list_ind[4])
ll = [12, 2, 45]
print(list_ind[1].sort())
ll.sort()
print(ll)
a = [5, 2, 3, 1, 4]
a.sort()
a

None
[2, 12, 45]


[1, 2, 3, 4, 5]

In [6]:
# sub block
df = pd.DataFrame(numofisg)                 
df.to_excel('210330_l9d2.xlsx', engine="xlsxwriter", header=False, index=False)



FileCreateError: [Errno 13] Permission denied: '210330_l9d2.xlsx'

In [22]:


# all posible values of group numbers
lenumeration = [i for i in range(0,lnum)] 

mysetup = '''
import numpy as np; from itertools import combinations; import itertools;import pandas as pd;
dim = 4
data = pd.read_csv('feeley2012_d4_testT.csv', sep=',')
lnum = data.shape[1]-1
data = np.array(data.iloc[:,0:lnum+1])
lenumeration = [i for i in range(0,lnum)] 
'''
mycode = '''
cnt = 0
for z in range(2,lnum):
#for z in range(3,4):
    lcombinations = list(combinations(range(0, lnum), z))
    # here lcombinations contain values for indexing matrix. from 0
    # posible combinatins of groups
    #print("lcombinations", lcombinations)
    tbl_k = np.empty((dim**z,dim**(lnum-z)))
    tbl_k.fill(np.nan)
    #print(tbl_k)
    for j in range(0, len(lcombinations)):
    #for j in range(0, 1):
        #print("j: ", j)
        # combine all posible tables of K on entered data
        #print(lcombinations[j])
        colfilled = []
        seen = set()
        for x in range(0,len(data)):
            # fill table K from data string by sting
            #print(data[x,lcombinations[j]])
            # get coordinate in nondecimal representation of string
            data[x,lcombinations[j]]
            # get coordinate in nondecimal representation of column
            reminder = list(set(lenumeration)-set(lcombinations[j])) 
            data[x,reminder]
            #print(data[x,lcombinations[j]])
            #print(data[x,reminder])
            # need to place F value in Ktable to selected coordinates
            c1 = "".join([str(xx) for xx in data[x,lcombinations[j]]])
            c2 = "".join([str(xx) for xx in data[x,reminder]])
            c2_t = int(c2[::-1], base = dim)
            #print(int(c1[::-1], base = dim)," ", c2_t)
            #print(int(c2[::-1], base = dim))
            tbl_k[int(c1[::-1], base = dim), c2_t] = data[x,lnum]
            # попутно можно записать все столбцы в которых есть значения, соотв. другие м.б. удал.
            if c2_t not in seen:
                seen.add(c2_t)
                colfilled.append(c2_t)
#print("uniq col ", len(colfilled))
#print(colfilled)  
tbl_k_s = tbl_k[:,colfilled]
#print(tbl_k_s[0:30,:])
'''
mycode2 = '''
cnt = 0
#for z in range(2,lnum):
for z in range(8,9):
    lcombinations = list(combinations(range(0, lnum), z))
    # here lcombinations contain values for indexing matrix. from 0
    # posible combinatins of groups
    #print("lcombinations", lcombinations)
    tbl_k = np.empty((dim**z,dim**(lnum-z)))
    tbl_k.fill(np.nan)
    #print(tbl_k)
    #for j in range(0, len(lcombinations)):
    for j in range(0, 1):
        #print("j: ", j)
        # combine all posible tables of K on entered data
        #print(lcombinations[j])
        colfilled = []
        seen = set()
        for x in range(0,len(data)):
            # fill table K from data string by sting
            #print(data[x,lcombinations[j]])
            # get coordinate in nondecimal representation of string
            data[x,lcombinations[j]]
            # get coordinate in nondecimal representation of column
            reminder = list(set(lenumeration)-set(lcombinations[j])) 
            data[x,reminder]
            #print(data[x,lcombinations[j]])
            #print(data[x,reminder])
            # need to place F value in Ktable to selected coordinates
            c1 = "".join([str(xx) for xx in data[x,lcombinations[j]]])
            c2 = "".join([str(xx) for xx in data[x,reminder]])
            c2_t = int(c2[::-1], base = dim)
            #print(int(c1[::-1], base = dim)," ", c2_t)
            #print(int(c2[::-1], base = dim))
            tbl_k[int(c1[::-1], base = dim), c2_t] = data[x,lnum]
            # попутно можно записать все столбцы в которых есть значения, соотв. другие м.б. удал.
            if c2_t not in seen:
                seen.add(c2_t)
                colfilled.append(c2_t)
#print("uniq col ", len(colfilled))
#print(colfilled)  
tbl_k_s = tbl_k[:,colfilled]
#print(tbl_k_s[0:30,:])
'''
print (timeit.timeit(setup = mysetup,
                    stmt = mycode,
                     number = 10)) 
# print (timeit.timeit(setup = mysetup,
#                      stmt = mycode2,
#                      number = 1000)) 

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 