In [1]:
'''Analisis of equivalency groups on conflict basis'''
# take care about param types
import re
#import functions_is as fis

import numpy as np
import pandas as pd
import string # for int2base

from itertools import product
from itertools import combinations
import itertools
import timeit
import datetime
import copy
from collections import Counter

In [2]:
def listToString(list1):
    return (''.join(map(str, list1)))
def listToString_cmm(list1):
    return (','+','.join(map(str, list1))+',')

def list_getsome(vec, positions):
    list_n = []
    for y in positions:
        list_n.append(vec[y])
    #print("lnf", list_n)
    return(list_n)

def diversity_num(vec, dim):
    # return num of different digits without nans
    # быстрее будет удалить сперва наны
    dvst = 0
    for i in range(0, dim):
        for j in range(0, len(vec)):
            if vec[j] == i:
                dvst += 1
                break
    return dvst
#len(set(tbl_merged[~np.isnan(tbl_merged[:,p]),p]))

def diversity_vec(vec, dim):
    dvst = []
    for i in range(0, dim):
        for j in range(0, len(vec)):
            if vec[j] == i:
                dvst.append(i)
                break
    return dvst

# diversity_vec_wnan # from collections import Counter
lst1 = Counter().keys() 
list()
    


[]

In [3]:
#data_ini = pd.read_csv('210805_postcode35_data_l6.csv', sep=';', header=None)
#data_ini = pd.read_csv('02_arctic_5x3_201223_data.csv', sep=';', header=None)
data_ini = pd.read_csv('freeley_tab_d4_cl.csv', sep=';', header=None)
print(data_ini)
# data should contain only leaves and K columns, it is format
# test if there are duplicates 
#data_ini.iloc[:,0:12].duplicated()
#print(data_ini[data_ini.iloc[:,0:12].duplicated(keep = False)])

    0   1   2   3   4   5   6   7   8   9   10
0    1   0   0   1   1   1   1   1   0   0   2
1    1   0   0   1   1   1   1   1   2   0   0
2    1   0   0   1   1   1   1   1   1   0   2
3    0   0   1   1   1   1   0   1   1   0   2
4    1   1   1   1   1   1   0   0   0   0   2
5    1   0   1   1   1   1   0   0   0   1   2
6    1   0   1   1   1   1   0   0   0   0   1
7    2   1   2   1   1   1   1   1   1   0   2
8    2   1   1   1   1   1   1   1   0   0   2
9    2   1   1   1   0   1   1   1   1   0   2
10   2   1   1   1   1   1   1   1   1   0   2
11   1   1   2   1   1   1   0   1   2   1   2
12   1   1   2   1   1   1   0   1   2   0   0
13   0   0   1   0   0   1   0   0   1   0   1
14   0   0   1   1   1   1   0   1   2   0   2
15   0   0   1   1   1   0   0   1   2   1   1
16   0   0   1   1   1   0   0   1   1   1   2
17   1   0   1   1   1   1   1   1   0   0   2
18   1   0   1   1   1   1   1   1   1   0   2
19   1   0   2   0   1   1   0   0   0   0   2
20   1   0   

In [4]:
# test if the set of examples can be realised 
# with incopmlete techniqe




#dim = 4
#load incomplete data
#data = pd.read_csv('feeley2012_cl_d4.csv', sep=',')
#data = pd.read_csv('210409_id_arctic_l5_datatable.csv', sep=',')
#data = pd.read_csv('02_arctic_5x3_201223_data.csv', sep=';')
#print(data)
# data should contain only leaves and K columns, it is format
#data.duplicated()
lnum = data_ini.shape[1]-1
print("lnum = ", lnum)
data = np.array(data_ini.iloc[:,0:lnum+1])
#print("data: \n" ,data)
dim = 1+data.max()-data.min()
print("dim = ", (data.max()-data.min())+1)
#print("K: " ,data[:,lnum-1])
print("\n")

# all posible values of group numbers
lenumeration = [i for i in range(0,lnum)] 

len_combinations = 0
for i in range(2,lnum):
    lcombinations = list(combinations(range(1, lnum+1), i))
    len_combinations += len(lcombinations)

dfnumofisg = pd.DataFrame(
    {
        "name": np.array(len_combinations, dtype="str"),
        "val": np.empty(len_combinations, dtype="int32"),
    }
)

print("number of set | set on x leaves")
cnt = 0
for i in range(2,lnum):
    lcombinations = list(combinations(range(1, lnum+1), i))
    # posible combinatins of groups
    print(i-1, lcombinations)
    #lcombinations =  lcombinations + 1
    #print(i-2, lcombinations)
    for j in range(len(lcombinations)):
        #print("lcombinations[i] ", lcombinations[i])
        #numofisg[cnt,0] = int(''.join(map(str, lcombinations[i])))
        dfnumofisg.iat[cnt,0] = ' '.join(map(str, lcombinations[j]))
        dfnumofisg.iat[cnt,1] = 0
        #print("dfnumofisg[i] ", dfnumofisg.iloc[cnt,:])
        cnt += 1

# # default values 
# numofgroup = 2
# numberofvalue = 1
# # enter dialog
# numofgroup = input('Enter number of group:') 
# numofgroup = int(numofgroup)+2
# numberofvalue = input('Enter number of value in group:') 
# numberofvalue = int(numberofvalue)
# print("\n")



# form table K
cntisgstore = 0
for numofgroup in range(2,lnum):
    lcombinations = list(combinations(range(0, lnum), numofgroup))
    lcombinations_p = list(combinations(range(1, lnum+1), numofgroup))
    #print("lcombinations", lcombinations)
    for numberofvalue in range(0, len(lcombinations)):
        print("group of leaves investigated: ", lcombinations_p[numberofvalue])
        tbl_k = np.empty((dim**(numofgroup),dim**(lnum-numofgroup)))
        tbl_k.fill(np.nan)
        colfilled = []
        seen = set()
        # fill table K from data string by sting (x)
        for x in range(0,len(data)):
            #print(data[x,lcombinations[j]])
            # get coordinate in nondecimal representation of string
            data[x,lcombinations[numberofvalue]]
            # get coordinate in nondecimal representation of column
            reminder = list(set(lenumeration)-set(lcombinations[numberofvalue])) 
            data[x,reminder]
            # need to place F value in Ktable to selected coordinates
            c1 = "".join([str(xx) for xx in data[x,lcombinations[numberofvalue]]])
            c2 = "".join([str(xx) for xx in data[x,reminder]])
            c2_t = int(c2[::-1], base = dim)
            tbl_k[int(c1[::-1], base = dim), c2_t] = data[x,lnum]
            # попутно можно записать все столбцы в которых есть значения, соотв. другие м.б. удал.
            if c2_t not in seen:
                seen.add(c2_t)
                colfilled.append(c2_t) 
        colfilled.sort()
        tbl_k_s = tbl_k[:,colfilled]
        # del nan rows
        rows_nan = np.all(np.isnan(tbl_k_s), axis = (1))
        tbl_k_s = tbl_k_s[~rows_nan,:]
        numbers = [int(i) for i in range(1,len(tbl_k_s)+1)]
        numbers_col = [int(i) for i in range(0,tbl_k_s.shape[1]+1)]
        temp_k = np.hstack((np.array(numbers).reshape(len(tbl_k_s),1), tbl_k_s))
        temp_k = np.vstack((np.array(numbers_col).reshape(1,temp_k.shape[1]), temp_k))
        #print(tbl_k_s)
        print(temp_k)

        # for now it is necessary to analyze whether the given alphabet is enough
        list_ind = [[i for i in range(tbl_k_s.shape[0])]]
        inigroup = 1

        for r in range(tbl_k_s.shape[1]):
            # select a column, from back because extend used further
            # checklist - digits in curr col
            if diversity_num(tbl_k_s[:,r], dim) > 1:
                # if there is conflict of type 1 = more than 1 different digit in col
                #checklist = tbl_k_s[:,r]
                checklist = copy.deepcopy(tbl_k_s[:,r])
                checklist_pos = 0
                for z in range(len(list_ind)-1,-1,-1): 
                    # select a range in list_ind
                    # rev list - это связано с тем что del удаляет с конца
                    # в этой версии это не нужно
                    ind_t = []
                    flag_del_inigroup = 0
                    nan_counted = 0
                    for w in range(dim):
                        # search for every simbol in alphabet in column                      
                        range_in_range = np.where(tbl_k_s[list_ind[z],r] == w)[0].tolist()
                        #if r > 0 and len(range_in_range) and not nan_counted:
                        if not inigroup and len(range_in_range) and not nan_counted:
                            # inigroup for don't count nans when inigroup activated
                            plus_na = np.argwhere(np.isnan(tbl_k_s[list_ind[z],r]))
                            plus_na = list(itertools.chain(*plus_na))
                            range_in_range = list(itertools.chain(*[range_in_range, plus_na]))
                            nan_counted = 1
                        if len(range_in_range):
                            range_in_range = list_getsome(list_ind[z], range_in_range)
                            checklist[range_in_range] = np.nan
                            ind_t.append(range_in_range)        
                            flag_del_inigroup = 1

                    if flag_del_inigroup:
                        del list_ind[z]
                        flag_del_inigroup = 0
                        inigroup = 0
                    # sort list for further includes and dubles checking
                    for c in range(len(ind_t)):
                        ind_t[c].sort()
                    list_ind.extend(ind_t)
                # seek for opportunity to expand eqg by new digits
                # checklist_pos - digits in checklist
                if ~np.isnan(checklist).all():
                    # test if there are not nans
                    # каждую позицию из разнообразия нужно приклеить без противоречия
                    # берем доступные числа из групп столбца и расширяем группы по ним
                    checklist_pos = np.argwhere(~np.isnan(checklist))#[0].tolist()
                    checklist_pos = list(itertools.chain(*checklist_pos))                
                    # need to sort list_ind for groups with digits go first
                    zzt = 0
                    cnt_zzt = 0
                    while cnt_zzt < len(list_ind)-1:
                        #if not len(set(tbl_k_s[list_ind[zzt],r])):
                        if not diversity_num(tbl_k_s[list_ind[zzt],r], dim):
                            #print(tbl_k_s[list_ind[zzt],r])
                            #print(len(set(tbl_k_s[list_ind[zzt],r])))
                            list_ind.append(list_ind[zzt])
                            del list_ind[zzt]
                        else: zzt += 1
                        cnt_zzt += 1
                    for zz in range(len(list_ind)):
                        ind_tt = list_ind[zz]
                        cnt_j = 0 
                        for j in checklist[checklist_pos]:
                            j = int(j)
                            ldiv = diversity_vec(tbl_k_s[ind_tt,r], dim)
                            # проверка ГЭ на наличие символа отличного от того для которого мы ищем группу                           
                            # сформировать список без j и искать вхождение из ldiv в него
                            list_without_j = [i for i in range(dim)]
                            del list_without_j[np.nonzero(np.array(list_without_j) == j)[0][0]]
                            if any(item in ldiv for item in list_without_j):
                                cnt_j += 1
                                continue
                            else:
                                list_ind[zz].append(checklist_pos[cnt_j])
                                checklist[checklist_pos[cnt_j]] = np.nan
                                checklist_pos = np.argwhere(~np.isnan(checklist))#[0].tolist()
                                checklist_pos = list(itertools.chain(*checklist_pos))
                #else # если в ГЭ нет номера из checklist, то добваить группу
                # проверить остались ли свободные числа in checklist
                if ~np.isnan(checklist).all():
                    # для каждого отдельного номинала своя группа
                    ldiv2 = diversity_vec(checklist, dim)
                    for i in ldiv2:
                        range_in_range2 = np.where(checklist == i)[0].tolist()
                        list_ind.append(range_in_range2)
        print("final partition: ", list_ind)  
        print("groups found = ", len(list_ind))
        print("\n")  
        
        #postanalisys: check if result may be merged for each pair of groups
        q = 0
        while q <= len(list_ind)-2:
            flag_onse = 1
            u = q + 1
            while u <= len(list_ind)-1:
                tbl_merged = np.vstack((tbl_k_s[list_ind[q],:], tbl_k_s[list_ind[u],:]))
                #print(tbl_merged)
                for p in range(tbl_merged.shape[1]):
                    if len(set(tbl_merged[~np.isnan(tbl_merged[:,p]),p])) > 1:
                        break           
                    if p == tbl_merged.shape[1]-1:
                        # was no break till ther end, so found 2 groups that can be merged
                        if flag_onse:
                            print("in result of postanalysis found opportunity for merge")
                            flag_onse = 0
                        print(list_ind[q], list_ind[u])
                        #t = list(itertools.chain(*[list_ind[q], list_ind[u]]))
                        list_ind.append(list(itertools.chain(*[list_ind[q], list_ind[u]])))
                        del list_ind[q]
                        del list_ind[u-1]
                        #list_ind.append(t)
                        print("final partition: ", list_ind)
                        print("groups found = ", len(list_ind))
                        print("\n")
                u += 1
            q += 1
        dfnumofisg.iat[cntisgstore,1] = len(list_ind)
        cntisgstore += 1
    

print("\n")
print("list of groups: \n", dfnumofisg)



lnum =  10
dim =  4


number of set | set on x leaves
1 [(1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (6, 7), (6, 8), (6, 9), (6, 10), (7, 8), (7, 9), (7, 10), (8, 9), (8, 10), (9, 10)]
2 [(1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 2, 6), (1, 2, 7), (1, 2, 8), (1, 2, 9), (1, 2, 10), (1, 3, 4), (1, 3, 5), (1, 3, 6), (1, 3, 7), (1, 3, 8), (1, 3, 9), (1, 3, 10), (1, 4, 5), (1, 4, 6), (1, 4, 7), (1, 4, 8), (1, 4, 9), (1, 4, 10), (1, 5, 6), (1, 5, 7), (1, 5, 8), (1, 5, 9), (1, 5, 10), (1, 6, 7), (1, 6, 8), (1, 6, 9), (1, 6, 10), (1, 7, 8), (1, 7, 9), (1, 7, 10), (1, 8, 9), (1, 8, 10), (1, 9, 10), (2, 3, 4), (2, 3, 5), (2, 3, 6), (2, 3, 7), (2, 3, 8), (2, 3, 9), (2, 3, 10), (2, 4, 5), (2, 4, 6), (2, 4, 7), (2, 4, 8), (2, 4, 9), (2, 4, 10), (2, 5, 6), (2, 5, 7), 

final partition:  [[0], [7], [1, 3], [5], [6, 8, 10], [4, 9]]
groups found =  6


in result of postanalysis found opportunity for merge
[0] [1, 3]
final partition:  [[7], [5], [6, 8, 10], [4, 9], [0, 1, 3]]
groups found =  5


group of leaves investigated:  (3, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37. 38. 39.]
 [ 1.  0. nan nan nan nan nan nan  2.  2. nan nan  2. nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan
  nan nan  0. nan]
 [ 2. nan nan nan  1.  2.  1.  1.  2.  2.  2.  2.  2.  2.  2.  1.  1.  0.
  nan  1.  0.  0.  1.  1. nan  1.  2.  2.  2.  1.  2.  2.  0.  2. nan nan
   1.  0.  1.  0.]
 [ 3. nan nan  2. nan nan nan nan nan nan nan nan nan nan  2. nan nan nan
   1. nan nan nan nan  0. nan nan nan nan nan nan nan  2. nan nan nan  0.
  nan nan nan nan]
 [ 4. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan 

final partition:  [[2, 5], [6], [4], [0, 3, 7]]
groups found =  4


group of leaves investigated:  (1, 2, 5)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan  0. nan nan nan nan nan nan
  nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan
  nan nan  2. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan]
 [ 3. nan nan nan nan nan nan nan nan nan nan nan  0. nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan]
 [ 4. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan  2. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan]
 [ 5. nan nan nan nan nan  2.  2. nan nan nan nan nan nan  1.  0. nan nan
  nan nan nan nan  0. 

final partition:  [[4], [2], [7], [3, 6]]
groups found =  4


in result of postanalysis found opportunity for merge
[4] [7]
final partition:  [[2], [3, 6], [4, 7]]
groups found =  3


group of leaves investigated:  (1, 5, 6)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37. 38. 39.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan  1. nan nan nan nan nan nan nan  1.
   0. nan nan nan nan nan nan  0. nan nan nan nan nan nan nan  2.  2. nan
  nan  1. nan nan]
 [ 3. nan nan nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan
  nan nan nan nan nan  1. nan nan nan nan nan nan  1. nan nan nan nan nan
  nan nan nan nan]
 [ 4. nan nan nan nan nan nan nan nan nan nan nan nan nan  1.  0. nan nan
  nan nan nan nan nan nan nan nan

final partition:  [[2, 5, 6], [7, 8], [9], [3, 10]]
groups found =  4


in result of postanalysis found opportunity for merge
[7, 8] [3, 10]
final partition:  [[2, 5, 6], [9], [7, 8, 3, 10]]
groups found =  3


group of leaves investigated:  (2, 3, 8)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan]
 [ 2. nan nan nan nan  1. nan nan nan  1. nan nan  1. nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan  0.  2. nan nan nan nan
  nan nan]
 [ 3. nan nan nan nan  2. nan nan nan nan nan nan  0. nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan]
 [ 4. nan nan  2. nan nan nan nan nan nan nan nan nan nan nan nan nan nan
   1. nan nan nan nan nan nan nan nan 

group of leaves investigated:  (2, 7, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34.]
 [ 1.  0. nan  2.  1. nan nan nan  2. nan  2. nan nan nan  1. nan  1. nan
  nan nan nan  0.  1. nan nan nan nan  0. nan nan  2. nan nan nan  0.]
 [ 2. nan nan nan  2.  1. nan nan nan  2. nan  2. nan nan  0. nan  0. nan
  nan nan nan  1. nan nan  0. nan  2. nan nan nan nan nan nan  0. nan]
 [ 3. nan nan nan  1. nan nan  2. nan  2. nan  2. nan nan nan  1. nan nan
   2. nan  2. nan  2. nan nan nan nan nan nan  0.  0.  1. nan nan nan]
 [ 4. nan nan nan nan nan  2. nan nan nan  2.  2.  1.  2. nan nan nan  1.
  nan  2. nan  1.  2.  2. nan  2. nan nan  1. nan nan nan  0. nan nan]
 [ 5. nan  0. nan  2. nan nan nan nan nan nan nan nan nan nan nan  2. nan
  nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan nan nan]
 [ 6. nan nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan 

final partition:  [[9, 8], [10], [7], [1, 3, 6]]
groups found =  4


in result of postanalysis found opportunity for merge
[9, 8] [7]
final partition:  [[10], [1, 3, 6], [9, 8, 7]]
groups found =  3


group of leaves investigated:  (3, 7, 9)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan  2. nan nan  2. nan nan
  nan nan nan nan nan nan]
 [ 2. nan nan nan nan  1.  2. nan  1. nan nan nan  2. nan nan  2. nan  0.
   2. nan  2. nan nan nan]
 [ 3. nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan]
 [ 4. nan nan nan nan nan nan nan nan nan nan nan nan  2. nan nan nan nan
  nan nan nan nan nan nan]
 [ 5. nan nan nan nan  1. nan nan nan  2.  2. nan nan  2.  2.  2.  1. nan
  nan nan nan nan nan nan]
 [ 6. nan nan nan nan nan nan nan nan nan nan nan nan nan nan  2. nan nan
  nan nan nan nan nan nan]
 [ 7. nan  1.  0. nan nan nan  1.  0. nan nan nan  

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37. 38. 39.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan nan nan
   1. nan  0. nan nan nan nan nan nan  0. nan nan nan nan nan nan  2.  2.
  nan  1. nan nan]
 [ 3. nan nan nan nan nan nan nan nan nan nan nan nan nan  1.  0. nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan  0. nan nan nan
  nan nan nan nan]
 [ 4. nan  2.  1.  2.  2. nan  2.  2. nan nan  2. nan nan nan nan nan nan
   0.  1.  1. nan nan  0. nan  2. nan  2. nan nan  0.  0. nan  2. nan nan
   2. nan nan  2.]
 [ 5. nan nan nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan
  nan nan nan nan  1. nan nan nan nan nan nan  1. nan nan nan nan nan nan
  nan nan nan nan

final partition:  [[7, 8], [0], [5, 6], [3], [1, 10], [4], [2, 9]]
groups found =  7


in result of postanalysis found opportunity for merge
[7, 8] [0]
final partition:  [[5, 6], [3], [1, 10], [4], [2, 9], [7, 8, 0]]
groups found =  6


in result of postanalysis found opportunity for merge
[3] [4]
final partition:  [[5, 6], [1, 10], [2, 9], [7, 8, 0], [3, 4]]
groups found =  5


group of leaves investigated:  (8, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28.]
 [ 1.  0. nan nan nan nan  2. nan nan nan  1. nan  2. nan nan nan nan nan
  nan nan nan nan nan  1. nan nan nan nan nan]
 [ 2. nan nan  1. nan nan nan  2.  2.  2. nan nan  2. nan nan nan nan  2.
   2. nan nan  2. nan  2.  2.  2.  1.  2. nan]
 [ 3. nan nan nan  1.  0. nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan  1. nan nan nan nan nan nan nan nan]
 [ 4. nan  1.  0. nan nan nan nan nan  0.  1.  1. nan  0. nan nan  2.  1.
   2.  2. nan  2. 

final partition:  [[3, 8], [0, 6], [1, 2, 10], [4, 5, 7, 9]]
groups found =  4


group of leaves investigated:  (1, 2, 5, 9)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan  0. nan
  nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan nan nan  2. nan nan nan
  nan nan nan nan]
 [ 3. nan nan nan nan nan nan nan  2.  2. nan nan nan nan nan nan nan nan
  nan nan nan nan]
 [ 4. nan nan  2.  1. nan  1. nan nan nan nan nan nan  2.  2. nan nan  2.
  nan nan nan nan]
 [ 5. nan nan nan nan nan nan  1. nan nan nan nan nan nan  2. nan nan nan
   2. nan nan nan]
 [ 6. nan nan nan  2. nan nan nan  2.  2. nan nan nan nan  2.  2. nan nan
  nan nan nan nan]
 [ 7. nan nan nan nan nan nan nan nan nan nan nan  2. nan  1. nan nan nan
  nan nan nan nan]
 [ 8. nan  1. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan]
 [ 9. nan nan nan nan nan nan nan nan 

final partition:  [[2, 20, 21, 23], [14, 8, 16], [7, 15, 22], [13], [4, 6, 11], [3, 5, 17, 18, 19], [12]]
groups found =  7


in result of postanalysis found opportunity for merge
[14, 8, 16] [13]
final partition:  [[2, 20, 21, 23], [7, 15, 22], [4, 6, 11], [3, 5, 17, 18, 19], [12], [14, 8, 16, 13]]
groups found =  6


in result of postanalysis found opportunity for merge
[4, 6, 11] [14, 8, 16, 13]
final partition:  [[2, 20, 21, 23], [7, 15, 22], [3, 5, 17, 18, 19], [12], [4, 6, 11, 14, 8, 16, 13]]
groups found =  5


group of leaves investigated:  (1, 3, 4, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan nan  1.  0. nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 3. nan nan  2. nan nan nan nan nan nan na

final partition:  [[0, 2, 22, 5, 12], [16, 17, 19, 23], [7], [9], [4], [8], [1, 3, 6, 13, 24, 25], [10, 15, 18, 20, 21, 14]]
groups found =  8


in result of postanalysis found opportunity for merge
[0, 2, 22, 5, 12] [9]
final partition:  [[16, 17, 19, 23], [7], [4], [8], [1, 3, 6, 13, 24, 25], [10, 15, 18, 20, 21, 14], [0, 2, 22, 5, 12, 9]]
groups found =  7


in result of postanalysis found opportunity for merge
[7] [4]
final partition:  [[16, 17, 19, 23], [8], [1, 3, 6, 13, 24, 25], [10, 15, 18, 20, 21, 14], [0, 2, 22, 5, 12, 9], [7, 4]]
groups found =  6


in result of postanalysis found opportunity for merge
[1, 3, 6, 13, 24, 25] [0, 2, 22, 5, 12, 9]
final partition:  [[16, 17, 19, 23], [8], [10, 15, 18, 20, 21, 14], [7, 4], [1, 3, 6, 13, 24, 25, 0, 2, 22, 5, 12, 9]]
groups found =  5


group of leaves investigated:  (1, 4, 5, 6)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36.

final partition:  [[3], [5, 6, 8], [4, 7], [2, 9]]
groups found =  4


group of leaves investigated:  (1, 5, 6, 9)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan
  nan nan nan nan nan  2. nan nan nan]
 [ 3. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
   2. nan nan nan nan nan nan nan nan]
 [ 4. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan  0. nan nan nan nan nan nan]
 [ 5. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan  2.
  nan nan nan nan nan nan nan nan nan]
 [ 6. nan nan nan nan nan nan nan nan  2. nan  2. nan nan nan nan nan nan
   2. nan nan nan nan nan nan nan nan]
 [ 7. nan nan nan  2.  1.  2. nan  1. nan  2. nan  2. nan nan nan  2.  2.
   2.  2. nan  2. na

final partition:  [[5, 7, 12, 19, 11], [3, 20], [2, 9, 17, 18], [0, 14], [1], [4, 10, 15, 16, 21], [8], [13, 6]]
groups found =  8


in result of postanalysis found opportunity for merge
[3, 20] [2, 9, 17, 18]
final partition:  [[5, 7, 12, 19, 11], [0, 14], [1], [4, 10, 15, 16, 21], [8], [13, 6], [3, 20, 2, 9, 17, 18]]
groups found =  7


in result of postanalysis found opportunity for merge
[1] [13, 6]
final partition:  [[5, 7, 12, 19, 11], [0, 14], [4, 10, 15, 16, 21], [8], [3, 20, 2, 9, 17, 18], [1, 13, 6]]
groups found =  6


in result of postanalysis found opportunity for merge
[8] [3, 20, 2, 9, 17, 18]
final partition:  [[5, 7, 12, 19, 11], [0, 14], [4, 10, 15, 16, 21], [1, 13, 6], [8, 3, 20, 2, 9, 17, 18]]
groups found =  5


group of leaves investigated:  (1, 8, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan]
 [ 2. nan nan nan nan nan 

final partition:  [[11, 14], [3, 8, 9, 12], [5], [1, 6, 10, 13], [2, 15]]
groups found =  5


group of leaves investigated:  (2, 3, 7, 8)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan  1. nan nan nan  1. nan nan nan nan nan nan
  nan nan nan nan nan nan  0.  2. nan nan nan nan]
 [ 3. nan nan nan nan nan nan  2. nan nan nan  0. nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 4. nan nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 5. nan nan nan nan nan nan  1. nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 6. nan nan nan nan nan nan nan nan nan nan nan nan nan  1. nan nan nan
  nan nan nan nan nan nan nan nan nan 

final partition:  [[5], [8], [0, 2], [1, 3, 6], [9, 10, 11]]
groups found =  5


in result of postanalysis found opportunity for merge
[8] [9, 10, 11]
final partition:  [[5], [0, 2], [1, 3, 6], [8, 9, 10, 11]]
groups found =  4


group of leaves investigated:  (2, 4, 8, 9)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26.]
 [ 1.  0. nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan
  nan nan nan  0. nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan  1. nan nan nan nan nan nan nan nan  1. nan
  nan nan nan nan nan  2. nan nan nan]
 [ 3. nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 4. nan nan nan  2. nan  2. nan nan nan nan nan  2. nan  2. nan  2. nan
  nan nan nan nan nan nan nan nan nan]
 [ 5. nan  1. nan nan  2. nan  2. nan nan nan  2. nan nan nan  2.  2.  1.
   2. nan  2. nan nan nan nan nan nan]
 [ 6. nan nan  1. nan nan nan nan nan nan nan na

final partition:  [[5], [7, 14, 15], [10], [4], [2, 3, 6, 8, 11], [1, 9, 12, 13]]
groups found =  6


in result of postanalysis found opportunity for merge
[5] [4]
final partition:  [[7, 14, 15], [10], [2, 3, 6, 8, 11], [1, 9, 12, 13], [5, 4]]
groups found =  5


group of leaves investigated:  (2, 6, 8, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan  2. nan nan nan  1. nan nan nan  1. nan nan  1. nan nan nan
  nan nan nan  1. nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan  2. nan nan nan nan nan nan  0. nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 4. nan nan nan nan nan nan nan nan nan nan nan nan nan nan  1. nan nan
  nan nan nan nan nan nan nan nan nan  0. nan nan nan

final partition:  [[5], [8, 6, 13], [9], [2, 12, 14], [4]]
groups found =  5


group of leaves investigated:  (3, 4, 8, 9)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan  0. nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan]
 [ 4. nan nan nan nan nan nan  1. nan  2. nan nan nan nan  1. nan nan nan
  nan nan nan  2. nan nan nan nan]
 [ 5. nan nan nan nan nan  2. nan nan  2. nan nan nan nan  2. nan nan nan
  nan nan nan nan nan nan nan nan]
 [ 6. nan nan  1. nan nan  2. nan nan  2.  2.  2. nan nan  2.  2.  2.  1.
  nan  2. nan nan nan nan nan nan]
 [ 7. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan  2. nan
  nan nan nan nan nan nan nan nan]
 [ 8.

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan  1. nan nan nan nan nan nan nan  1. nan
   0. nan nan  0. nan nan nan]
 [ 3. nan nan nan nan nan  2. nan nan  2. nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan]
 [ 4. nan nan  1.  2. nan  2. nan nan  2. nan  1.  0. nan nan nan  0.  1.
   1. nan nan  2. nan nan nan]
 [ 5. nan  2. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
   0. nan nan nan nan  0. nan]
 [ 6. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan  2. nan nan  0. nan nan]
 [ 7. nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan
  nan nan  1. nan nan nan  1.]
 [ 8. nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan nan  2.
  nan nan nan nan  0. nan nan]
 [ 9. nan nan  1. nan  2. nan  2.  2.  2.  1. nan nan n

final partition:  [[10], [11], [1, 3], [5], [7, 9, 12], [4, 8]]
groups found =  6


in result of postanalysis found opportunity for merge
[10] [11]
final partition:  [[1, 3], [5], [7, 9, 12], [4, 8], [10, 11]]
groups found =  5


in result of postanalysis found opportunity for merge
[5] [7, 9, 12]
final partition:  [[1, 3], [4, 8], [10, 11], [5, 7, 9, 12]]
groups found =  4


group of leaves investigated:  (4, 6, 7, 8)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
  36. 37. 38. 39. 40.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan  2. nan  1. nan  0. nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan  0. nan nan
  nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan  1. nan  2. nan nan nan nan nan na

final partition:  [[4, 5], [1, 2, 8, 9], [3, 7]]
groups found =  3


group of leaves investigated:  (5, 7, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan]
 [ 2. nan nan nan  2.  1.  2. nan  1. nan  2. nan  2.  2. nan nan  2. nan
  nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan nan nan nan nan nan nan nan  2. nan nan nan
  nan nan nan nan nan]
 [ 4. nan nan nan nan  1. nan nan nan  2. nan  2. nan nan  2.  2.  2.  1.
  nan  2. nan nan nan]
 [ 5. nan  1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan]
 [ 6. nan nan nan nan nan nan  1.  0. nan nan nan nan  0.  1.  1. nan nan
   0. nan nan nan  2.]
 [ 7. nan nan nan nan nan nan nan nan nan nan nan nan nan  2. nan nan  2.
  nan nan nan nan nan]
 [ 8. nan nan nan  1. nan nan nan nan  1. nan  2. nan nan  2.  1.  2.  2.
  nan nan  2. nan nan]
 [ 9. nan nan

final partition:  [[4, 8, 10, 13, 17, 19], [6, 9, 14], [12], [2, 3, 7, 15, 18, 20], [1, 11, 16]]
groups found =  5


in result of postanalysis found opportunity for merge
[6, 9, 14] [1, 11, 16]
final partition:  [[4, 8, 10, 13, 17, 19], [12], [2, 3, 7, 15, 18, 20], [6, 9, 14, 1, 11, 16]]
groups found =  4


group of leaves investigated:  (1, 2, 3, 5, 9)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan  0. nan nan nan nan]
 [ 3. nan nan nan nan nan nan nan nan  2. nan nan nan nan nan]
 [ 4. nan nan nan nan nan nan  2. nan nan nan nan nan nan nan]
 [ 5. nan nan nan nan nan nan nan nan  2. nan nan nan nan nan]
 [ 6. nan nan nan nan nan nan  2. nan nan nan nan nan nan nan]
 [ 7. nan nan nan nan nan nan  2. nan nan nan nan nan nan nan]
 [ 8. nan nan  1. nan  1. nan nan nan  2. nan  2. nan nan nan]
 [ 9. nan nan nan nan nan  1. nan nan  2. nan nan  2. nan nan]
 [10. nan nan 

final partition:  [[1, 4, 10, 11, 16, 17], [8, 21, 0], [14], [9, 15, 19], [7], [6], [3, 18], [5, 13]]
groups found =  8


in result of postanalysis found opportunity for merge
[1, 4, 10, 11, 16, 17] [14]
final partition:  [[8, 21, 0], [9, 15, 19], [7], [6], [3, 18], [5, 13], [1, 4, 10, 11, 16, 17, 14]]
groups found =  7


[8, 21, 0] [3, 18]
final partition:  [[9, 15, 19], [7], [6], [5, 13], [1, 4, 10, 11, 16, 17, 14], [8, 21, 0, 3, 18]]
groups found =  6


group of leaves investigated:  (1, 2, 4, 5, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan  0. nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan
  nan nan  2. nan nan nan nan nan nan nan nan]
 [ 4. n

final partition:  [[5], [1, 10], [4, 7, 12, 13, 17], [2, 3, 6], [9, 18], [8, 11, 14], [16]]
groups found =  7


in result of postanalysis found opportunity for merge
[5] [9, 18]
final partition:  [[1, 10], [4, 7, 12, 13, 17], [2, 3, 6], [8, 11, 14], [16], [5, 9, 18]]
groups found =  6


group of leaves investigated:  (1, 2, 5, 7, 8)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26.]
 [ 1.  0. nan nan nan nan nan nan  1. nan nan nan nan nan nan nan nan nan
  nan nan  0. nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan  0. nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 3. nan nan  2. nan  1. nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan  2. nan nan nan nan nan]
 [ 4. nan nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 5. nan nan nan nan  1. nan nan nan  1. nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan 

final partition:  [[5, 11, 25, 27, 26], [8, 19, 22, 23], [14, 15], [2, 3, 16, 21], [7], [6, 24], [4, 12], [1, 10, 13, 17, 18, 20]]
groups found =  8


in result of postanalysis found opportunity for merge
[5, 11, 25, 27, 26] [14, 15]
final partition:  [[8, 19, 22, 23], [2, 3, 16, 21], [7], [6, 24], [4, 12], [1, 10, 13, 17, 18, 20], [5, 11, 25, 27, 26, 14, 15]]
groups found =  7


in result of postanalysis found opportunity for merge
[7] [1, 10, 13, 17, 18, 20]
final partition:  [[8, 19, 22, 23], [2, 3, 16, 21], [6, 24], [4, 12], [5, 11, 25, 27, 26, 14, 15], [7, 1, 10, 13, 17, 18, 20]]
groups found =  6


group of leaves investigated:  (1, 3, 4, 5, 6)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan  1. nan nan nan nan nan  1.  0. nan nan  0. nan nan
  nan nan  2.  2. nan nan  1. nan nan]
 [

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan]
 [ 2. nan nan nan nan  1. nan nan  1.  0.  0. nan nan nan  2.  2. nan  1.
  nan]
 [ 3. nan nan nan nan nan  1.  0. nan nan nan nan  0. nan nan nan nan nan
  nan]
 [ 4. nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan]
 [ 5. nan nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan nan
  nan]
 [ 6. nan nan nan  2. nan nan nan  0.  1.  2. nan nan nan nan nan  2. nan
  nan]
 [ 7. nan  1.  2. nan  2. nan nan  1. nan nan nan nan  2. nan nan nan nan
  nan]
 [ 8. nan nan nan nan nan nan nan nan  0. nan nan nan nan nan nan nan nan
  nan]
 [ 9.  2. nan nan nan nan nan nan nan nan nan  0. nan nan nan nan nan nan
   2.]
 [10. nan nan nan nan nan nan nan nan  2.  0. nan nan nan nan nan nan nan
  nan]
 [11. nan nan nan nan  2. nan nan nan  1. nan  1. nan nan nan nan nan nan
  nan]
 [12. nan nan nan  2. nan na

final partition:  [[1, 12, 19, 23, 26, 7, 10, 20], [9, 13, 15, 25, 32, 2, 8, 14, 17], [4, 6, 11, 18, 27, 31, 33, 34], [0, 3, 5, 21, 22, 28, 29, 30], [24]]
groups found =  5


group of leaves investigated:  (1, 3, 7, 8, 9)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan nan  0. nan nan]
 [ 3. nan nan nan nan nan nan nan nan  1.  2. nan nan nan  2. nan]
 [ 4. nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan]
 [ 5. nan nan nan nan nan nan nan nan  1. nan nan nan nan nan nan]
 [ 6. nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan]
 [ 7. nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan]
 [ 8. nan nan  1. nan nan nan nan nan  2. nan nan  2. nan nan nan]
 [ 9. nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan]
 [10. nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan]
 [11. nan nan nan nan nan nan nan nan nan

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan
  nan  2. nan]
 [ 3. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan  0. nan
  nan nan nan]
 [ 4. nan nan nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan]
 [ 5. nan nan nan nan nan nan nan nan  2. nan  2. nan nan nan nan nan nan
  nan nan nan]
 [ 6. nan nan nan  1.  2. nan nan nan nan  2. nan  2. nan nan nan nan  2.
  nan nan nan]
 [ 7. nan nan nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan
  nan nan nan]
 [ 8. nan nan nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan
  nan nan nan]
 [ 9. nan nan nan  1. nan nan  2. nan  2. nan  2.  2.  2. nan nan nan nan
  nan nan nan]
 [10. nan nan nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan
  nan nan nan]
 [11. nan nan nan nan

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan  1.  0. nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan  2. nan nan  1.  2. nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan  1. nan nan nan nan nan nan  1. nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 4. nan  1. nan nan  2. nan  2. nan nan  1.  0. nan nan nan nan  0.  1.
   0. nan  0. nan nan  2. nan nan nan]
 [ 5. nan nan nan nan nan  2. nan  2. nan nan nan nan nan nan nan  1. nan
  nan  2. nan nan nan nan nan  0.  0.]
 [ 6. nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan  2. nan
  nan nan nan nan nan nan nan nan nan]
 [ 7. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan  2.
  nan nan nan nan nan nan nan nan nan]
 [ 8. nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan  1.
  nan nan nan nan nan 

final partition:  [[17], [7, 8, 14], [0, 12, 22, 24, 25, 23], [4, 6], [21], [1, 3, 5, 9, 11, 16, 18], [10, 15, 19, 20]]
groups found =  7


in result of postanalysis found opportunity for merge
[17] [21]
final partition:  [[7, 8, 14], [0, 12, 22, 24, 25, 23], [4, 6], [1, 3, 5, 9, 11, 16, 18], [10, 15, 19, 20], [17, 21]]
groups found =  6


group of leaves investigated:  (2, 3, 4, 6, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan
  nan  0. nan nan nan nan]
 [ 3. nan nan nan  1. nan nan nan nan  2. nan nan  0. nan nan nan nan nan
   1. nan nan nan nan  1.]
 [ 4. nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan nan nan
  nan nan nan nan nan nan]
 [ 5. nan nan nan nan nan nan nan nan nan  0. nan nan nan nan nan nan nan
  nan nan nan nan nan nan]
 [ 6

group of leaves investigated:  (2, 3, 5, 8, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan nan nan nan nan nan  0. nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 4. nan nan nan nan nan  1. nan nan  1. nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 5. nan nan nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 6. nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan  1. nan
  nan nan nan nan nan nan nan nan nan]
 [ 7. nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan
   2. nan nan nan nan nan nan nan nan]
 [ 8. nan nan nan nan nan nan nan nan nan nan na

final partition:  [[10, 14], [4, 8, 11], [1, 6, 9, 13], [2, 3]]
groups found =  4


group of leaves investigated:  (2, 4, 5, 7, 8)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan  1. nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan  0. nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan nan  0. nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 4. nan nan nan nan nan nan  1. nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan]
 [ 5. nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan 

final partition:  [[15], [9], [3], [7, 16], [1, 10], [6, 8, 11], [2, 4, 12], [0, 5, 13, 14, 17]]
groups found =  8


in result of postanalysis found opportunity for merge
[15] [3]
final partition:  [[9], [7, 16], [1, 10], [6, 8, 11], [2, 4, 12], [0, 5, 13, 14, 17], [15, 3]]
groups found =  7


in result of postanalysis found opportunity for merge
[2, 4, 12] [15, 3]
final partition:  [[9], [7, 16], [1, 10], [6, 8, 11], [0, 5, 13, 14, 17], [2, 4, 12, 15, 3]]
groups found =  6


group of leaves investigated:  (2, 5, 6, 7, 8)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan  1. nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan  0. nan nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan nan nan  0. nan nan nan nan nan nan nan nan
  nan nan n

final partition:  [[3, 6, 8, 18, 19, 20, 21, 22, 24], [7, 9, 10, 23, 2, 15], [4, 5, 12, 1, 25], [0, 16, 17], [11, 13], [14]]
groups found =  6


group of leaves investigated:  (3, 4, 5, 6, 7)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan  1. nan nan nan nan nan  1. nan  0. nan nan  0.
  nan nan nan nan nan  2.  2. nan  1. nan nan]
 [ 3. nan nan nan nan nan nan nan nan  1. nan  0. nan nan nan nan nan nan
  nan nan nan  0. nan nan nan nan nan nan nan]
 [ 4. nan  2. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan]
 [ 5. nan nan nan  2. nan nan  2. nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan]
 [ 6. nan  1.  2.  2. nan nan  2. nan nan nan nan  0.  1.  1. nan nan  2.
  nan na

final partition:  [[9, 13, 24], [1, 10], [0, 12, 15, 17, 18, 19, 21, 22, 25], [3, 4], [2, 6, 7, 14, 16, 20, 23], [11]]
groups found =  6


group of leaves investigated:  (3, 4, 7, 8, 9)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan  0. nan
  nan nan]
 [ 3. nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan
  nan nan]
 [ 4. nan nan nan nan nan nan nan nan nan  1. nan  2. nan nan nan nan  2.
  nan nan]
 [ 5. nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan nan nan
  nan nan]
 [ 6. nan nan nan nan nan nan nan nan  2. nan nan  2. nan nan nan nan nan
  nan nan]
 [ 7. nan nan  1. nan nan nan nan nan  2. nan nan  2. nan nan  2. nan nan
  nan nan]
 [ 8. nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan
  nan nan]
 [ 9. nan nan nan  2. nan  2. nan nan nan  2.  2.

final partition:  [[11, 13, 14, 9, 17], [16, 18], [7], [15], [12], [1, 3, 5, 8, 10]]
groups found =  6


in result of postanalysis found opportunity for merge
[11, 13, 14, 9, 17] [15]
final partition:  [[16, 18], [7], [12], [1, 3, 5, 8, 10], [11, 13, 14, 9, 17, 15]]
groups found =  5


group of leaves investigated:  (3, 6, 7, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan  1. nan nan]
 [ 3. nan nan nan nan nan nan nan  2. nan nan  2. nan]
 [ 4. nan nan nan  1.  2. nan nan  2. nan nan  2. nan]
 [ 5. nan nan  2. nan nan nan nan nan nan nan nan nan]
 [ 6. nan nan nan nan nan nan nan nan nan nan nan  2.]
 [ 7. nan nan nan nan nan nan nan nan  2. nan nan nan]
 [ 8. nan nan nan  1. nan  2. nan nan  2.  2.  2.  1.]
 [ 9. nan nan nan nan nan nan nan nan nan nan  2. nan]
 [10. nan nan nan nan nan nan nan  1. nan  0. nan nan]
 [11.  1.  0. nan nan nan nan nan  0.  1.  1. nan nan]
 [12.

final partition:  [[3, 4, 7, 10, 11, 13, 19, 24], [5, 9, 14, 16, 20, 21, 23], [1, 2, 8, 12, 15, 17, 18], [6, 22]]
groups found =  4


group of leaves investigated:  (4, 6, 8, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan  1. nan  2. nan nan nan nan nan nan nan nan
  nan  1. nan nan nan nan nan nan]
 [ 4. nan nan nan nan nan nan nan  1. nan nan nan nan nan nan nan nan nan
  nan nan nan nan  2. nan nan nan]
 [ 5. nan nan nan  2.  2.  2. nan nan  2. nan nan nan nan nan  2. nan  2.
  nan  2.  2.  2.  1. nan  2. nan]
 [ 6. nan  1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan  1. nan nan]
 [ 7. nan nan nan nan nan  1. nan  0. nan nan nan nan n

final partition:  [[0, 1, 14, 18, 23, 12, 16, 30, 33], [9, 22, 2, 6, 10, 13, 20, 24, 25, 27], [4, 5, 7, 8, 17, 28, 32, 31, 34], [11], [15, 21, 26, 29, 36], [35]]
groups found =  6


group of leaves investigated:  (1, 2, 3, 4, 6, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan  1.  0. nan nan nan nan nan]
 [ 3. nan nan nan nan nan  1.  0. nan nan nan nan nan nan]
 [ 4. nan nan nan nan nan nan nan nan nan nan  2.  1.  1.]
 [ 5. nan  1. nan nan nan nan nan nan nan nan nan nan nan]
 [ 6. nan  0. nan nan nan nan nan nan nan nan nan nan nan]
 [ 7. nan nan  2. nan  1. nan nan nan nan nan nan nan nan]
 [ 8. nan nan nan nan nan  2. nan nan nan nan nan nan nan]
 [ 9. nan nan nan nan nan nan nan nan nan nan  2.  2.  0.]
 [10. nan nan nan nan nan  2. nan nan nan nan nan nan nan]
 [11. nan nan nan nan nan  2.  0.  2. nan nan nan nan  0.]
 [12. nan nan  1.  1. nan nan  1. nan  2.  2.  2.  2.  1.]


final partition:  [[1, 3, 15, 23], [6, 9], [12], [2, 4, 5, 8, 10, 11, 14, 16, 22, 26], [20, 25, 7, 18, 24], [13, 17, 19, 21]]
groups found =  6


in result of postanalysis found opportunity for merge
[6, 9] [2, 4, 5, 8, 10, 11, 14, 16, 22, 26]
final partition:  [[1, 3, 15, 23], [12], [20, 25, 7, 18, 24], [13, 17, 19, 21], [6, 9, 2, 4, 5, 8, 10, 11, 14, 16, 22, 26]]
groups found =  5


group of leaves investigated:  (1, 2, 3, 5, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  0. nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan  2.]
 [ 3. nan nan nan nan nan nan  2. nan nan]
 [ 4. nan nan nan nan nan nan nan nan  2.]
 [ 5. nan nan nan nan nan nan  2. nan nan]
 [ 6. nan nan nan nan nan nan  2. nan nan]
 [ 7. nan nan  1. nan  1. nan nan nan  2.]
 [ 8. nan nan nan nan nan  1. nan nan  2.]
 [ 9. nan nan  2. nan nan nan  2. nan  2.]
 [10. nan nan nan nan nan nan nan  2.  1.]
 [11. nan  2. nan nan nan nan nan nan nan]
 [12. nan nan nan nan nan nan nan nan  2.]
 [

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan  1. nan  0. nan nan nan
  nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan  0. nan nan nan nan nan
  nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan  2.
  nan nan nan nan nan]
 [ 4. nan nan nan nan nan nan nan nan nan nan  1. nan nan  2. nan nan nan
  nan nan nan nan nan]
 [ 5. nan nan nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan
  nan nan nan nan nan]
 [ 6. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
   1. nan nan nan nan]
 [ 7. nan nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan nan
  nan nan nan nan nan]
 [ 8. nan nan  1.  0. nan  2.  1.  2. nan nan  2.  0.  2. nan nan nan nan
  nan nan nan nan nan]
 [ 9. nan nan nan nan nan nan nan nan nan nan nan  1. nan nan nan nan nan
  nan nan nan nan  0.]
 [10. nan  1.  0. nan  2. nan 

final partition:  [[2, 5, 17, 15], [6, 20, 34, 22], [7, 8, 19, 21, 31, 32, 35], [13, 14, 18, 25, 23], [3, 4, 10, 12, 16, 26, 33, 24], [1, 9, 11, 27, 28, 29, 30]]
groups found =  6


in result of postanalysis found opportunity for merge
[2, 5, 17, 15] [7, 8, 19, 21, 31, 32, 35]
final partition:  [[6, 20, 34, 22], [13, 14, 18, 25, 23], [3, 4, 10, 12, 16, 26, 33, 24], [1, 9, 11, 27, 28, 29, 30], [2, 5, 17, 15, 7, 8, 19, 21, 31, 32, 35]]
groups found =  5


group of leaves investigated:  (1, 2, 4, 8, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan  2. nan nan nan nan nan nan]
 [ 3. nan nan nan nan  1. nan nan nan nan nan  1. nan]
 [ 4. nan nan nan nan  2. nan nan nan nan nan nan nan]
 [ 5. nan nan nan  2.  2. nan nan nan nan nan nan nan]
 [ 6. nan nan nan nan nan nan nan nan  2.  2.  2. nan]
 [ 7. nan  1. nan nan nan nan nan nan nan nan  2. nan]
 [ 8. nan nan nan  2.  2. nan nan nan nan nan  2.  

final partition:  [[2, 5, 12, 23, 27, 28, 29, 30, 34, 26], [8, 31, 4, 7, 20, 33], [14, 16, 19, 21], [6, 17], [1, 3, 10, 13, 18, 24, 25, 32, 9, 15, 22]]
groups found =  5


group of leaves investigated:  (1, 2, 7, 8, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  0. nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan  2. nan  1. nan nan]
 [ 3. nan nan nan nan nan nan  2. nan nan]
 [ 4. nan nan nan nan nan nan  1. nan nan]
 [ 5. nan nan nan nan nan  2.  2. nan nan]
 [ 6. nan  1. nan nan nan nan nan nan nan]
 [ 7. nan nan nan nan nan  2.  2. nan nan]
 [ 8. nan nan nan  2. nan  2.  2. nan nan]
 [ 9. nan nan nan nan nan nan  2. nan nan]
 [10. nan nan nan nan nan nan  2.  2. nan]
 [11. nan  2. nan nan nan nan  1. nan nan]
 [12. nan nan  1. nan nan nan nan nan nan]
 [13. nan nan  0. nan nan nan nan nan nan]
 [14. nan nan nan nan  1. nan nan nan nan]
 [15. nan  1. nan nan nan nan  0. nan nan]
 [16. nan nan nan nan nan nan  1. nan nan]
 [17. nan  0. nan nan nan nan  1.  0. nan]
 [1

final partition:  [[7, 9, 16], [2, 6, 8, 12, 25, 26], [3, 13, 22, 27, 28], [0, 5, 11, 14, 18, 19, 20, 21, 29], [4, 10, 15, 17, 23, 24, 30]]
groups found =  5


group of leaves investigated:  (1, 3, 4, 6, 8, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan]
 [ 2. nan  1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan]
 [ 3. nan nan nan  2. nan nan nan nan nan nan nan nan nan  1. nan nan nan
  nan]
 [ 4. nan nan nan  1. nan nan  2. nan nan nan nan nan  1. nan nan nan nan
  nan]
 [ 5. nan nan nan nan  1.  0.  1.  0. nan nan nan nan nan nan nan nan nan
  nan]
 [ 6. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan  2.  1.
   1.]
 [ 7. nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan]
 [ 8. nan nan nan nan nan nan  2. nan nan nan nan nan  2.  2.  0. nan nan
  nan]
 [ 9. nan nan nan  2.  0.  2. nan  1. nan nan nan nan nan na

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan  1.  2. nan nan  1. nan]
 [ 3. nan nan nan  2. nan nan nan nan nan nan nan]
 [ 4. nan nan nan nan nan nan nan nan nan  2. nan]
 [ 5. nan nan nan nan nan  2. nan nan nan nan nan]
 [ 6. nan nan nan nan nan nan  2. nan nan  2. nan]
 [ 7. nan nan  1. nan nan  2. nan nan nan nan  2.]
 [ 8. nan nan nan nan nan nan  2. nan nan  2.  2.]
 [ 9. nan nan nan nan nan nan nan  2. nan nan  1.]
 [10. nan nan nan nan nan nan nan nan nan nan  2.]
 [11. nan nan nan  1.  0. nan nan nan nan nan nan]
 [12. nan nan nan nan nan nan nan nan  1. nan nan]
 [13. nan nan nan nan nan nan nan nan nan  2. nan]
 [14. nan nan nan nan nan nan nan nan nan nan  2.]
 [15. nan nan nan nan nan nan nan nan nan  2. nan]
 [16. nan  1.  0. nan nan  0.  1. nan nan nan  1.]
 [17. nan nan nan nan nan  1. nan nan nan  2.  2.]
 [18. nan nan nan nan nan nan nan  1. nan nan  2.]
 [19. nan nan nan nan nan nan  

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan nan]
 [ 3. nan nan nan nan nan  1.  2. nan nan nan nan nan nan  1. nan nan nan]
 [ 4. nan nan nan nan nan nan nan nan nan nan nan nan nan  2. nan nan nan]
 [ 5. nan nan  1.  2. nan  2. nan nan nan nan nan nan nan nan  2. nan nan]
 [ 6. nan nan nan nan  2. nan  2. nan nan nan nan nan  2.  2.  2. nan  2.]
 [ 7. nan nan nan nan nan nan nan nan nan nan nan  2. nan nan  1. nan nan]
 [ 8. nan nan nan nan nan  1.  0. nan nan nan nan nan nan nan nan nan nan]
 [ 9. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan  1. nan]
 [10. nan nan nan nan nan nan nan nan nan nan nan nan nan  2. nan nan nan]
 [11. nan nan nan nan nan nan nan nan nan nan nan nan nan nan  2. nan nan]
 [12. nan  1.  0. nan nan  0.  1. nan  0. nan nan nan nan nan  1. nan nan]
 [13. nan nan nan nan nan

final partition:  [[11, 18, 22, 23], [20, 15], [1, 4, 6, 10, 12, 19, 21], [8], [0, 13, 25, 27, 28, 26], [5, 7, 3, 9, 14, 17], [24]]
groups found =  7


in result of postanalysis found opportunity for merge
[20, 15] [24]
final partition:  [[11, 18, 22, 23], [1, 4, 6, 10, 12, 19, 21], [8], [0, 13, 25, 27, 28, 26], [5, 7, 3, 9, 14, 17], [20, 15, 24]]
groups found =  6


group of leaves investigated:  (2, 3, 4, 5, 6, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan]
 [ 2. nan nan nan nan nan nan nan  1. nan  0. nan nan nan nan nan nan nan
  nan nan nan]
 [ 3. nan nan nan nan nan  1. nan  0. nan nan nan nan nan  2. nan nan  1.
  nan nan  1.]
 [ 4. nan nan  1. nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan]
 [ 5. nan nan  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan]
 [ 6. nan nan nan nan nan nan nan nan nan nan

final partition:  [[2, 3, 5, 9, 11, 14, 15, 17, 18, 20, 13], [16], [1, 4, 6, 7, 10, 12], [22, 25, 23, 24], [21]]
groups found =  5


in result of postanalysis found opportunity for merge
[16] [21]
final partition:  [[2, 3, 5, 9, 11, 14, 15, 17, 18, 20, 13], [1, 4, 6, 7, 10, 12], [22, 25, 23, 24], [16, 21]]
groups found =  4


group of leaves investigated:  (2, 3, 4, 7, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan  2. nan nan nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan nan  2. nan nan]
 [ 4. nan nan nan nan nan nan nan nan  2. nan]
 [ 5. nan nan  1. nan nan nan nan  2. nan nan]
 [ 6. nan nan  2.  1. nan nan nan nan  2. nan]
 [ 7. nan nan nan nan nan nan nan nan  2. nan]
 [ 8. nan nan  1. nan nan  2. nan nan  2. nan]
 [ 9. nan nan nan nan  2. nan nan  2.  2.  1.]
 [10. nan nan nan nan nan nan nan nan  2. nan]
 [11. nan  1. nan nan nan nan nan nan nan nan]
 [12. nan  0. nan nan nan nan nan nan nan nan]
 [13. nan 

final partition:  [[2, 4, 10, 25, 32, 34, 35, 36, 18, 28], [0, 1, 3, 5, 8, 11, 12, 15, 17, 19, 20, 21, 22, 33, 37, 38, 39, 7, 23], [6, 13, 14, 16, 24, 30, 31], [9], [26, 27, 29]]
groups found =  5


in result of postanalysis found opportunity for merge
[2, 4, 10, 25, 32, 34, 35, 36, 18, 28] [9]
final partition:  [[0, 1, 3, 5, 8, 11, 12, 15, 17, 19, 20, 21, 22, 33, 37, 38, 39, 7, 23], [6, 13, 14, 16, 24, 30, 31], [26, 27, 29], [2, 4, 10, 25, 32, 34, 35, 36, 18, 28, 9]]
groups found =  4


group of leaves investigated:  (2, 3, 6, 8, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan  1. nan nan nan nan  1. nan]
 [ 3. nan nan nan  2. nan nan nan nan nan nan]
 [ 4. nan  2. nan nan nan nan nan nan nan nan]
 [ 5. nan nan  1. nan nan nan nan nan nan  2.]
 [ 6. nan nan  2. nan nan nan nan nan  2. nan]
 [ 7. nan nan nan  2. nan nan nan nan nan nan]
 [ 8. nan nan  2. nan  2. nan nan nan  2. nan]
 [ 9. nan nan nan  2. nan nan nan

final partition:  [[9, 12, 18, 22, 23], [1, 2, 4, 5, 8, 11, 13, 17, 20, 25, 26, 30, 32], [3, 6, 7, 10, 14, 15, 16, 19, 21, 24, 27, 28, 29, 31]]
groups found =  3


group of leaves investigated:  (2, 4, 6, 8, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan nan]
 [ 3. nan nan nan nan nan  1. nan nan nan nan nan nan nan  1. nan nan nan]
 [ 4. nan nan nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan]
 [ 5. nan nan nan nan  1. nan nan nan nan nan nan nan nan nan  2. nan nan]
 [ 6. nan nan  2. nan  2. nan nan nan nan  2. nan  2. nan  2. nan nan nan]
 [ 7. nan nan nan  2. nan  2. nan nan nan nan nan nan  2.  2.  1.  2. nan]
 [ 8. nan  1. nan nan nan nan nan nan nan nan nan nan nan nan nan  1. nan]
 [ 9. nan  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
 [10. nan nan nan nan  1. nan nan n

final partition:  [[18, 19], [16], [11, 22, 23, 14, 21], [0, 2, 5, 6, 7, 8, 9, 10, 15, 17, 20], [3, 4, 12, 13, 24]]
groups found =  5


in result of postanalysis found opportunity for merge
[18, 19] [16]
final partition:  [[11, 22, 23, 14, 21], [0, 2, 5, 6, 7, 8, 9, 10, 15, 17, 20], [3, 4, 12, 13, 24], [18, 19, 16]]
groups found =  4


group of leaves investigated:  (3, 4, 5, 7, 8, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan  1. nan  0. nan nan nan
  nan nan nan nan nan]
 [ 3. nan nan nan nan  2. nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan]
 [ 4. nan nan nan nan  1. nan  2. nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan]
 [ 5. nan nan nan nan nan nan nan nan nan nan nan nan  1. nan nan nan nan
  nan nan nan nan nan]
 [ 6. nan nan nan nan  1. nan

final partition:  [[0, 3, 4, 5, 13, 17, 20], [2, 10, 12], [6, 7, 8, 15, 16, 18, 1], [9, 11, 14, 19]]
groups found =  4


group of leaves investigated:  (4, 5, 6, 7, 8, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19. 20. 21. 22. 23. 24. 25. 26.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan nan nan nan nan  1. nan  0. nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 3. nan nan nan nan nan nan nan nan  2. nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 4. nan nan nan nan  1. nan  2. nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 5. nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan  1.
  nan nan nan nan nan nan nan nan nan]
 [ 6. nan nan nan nan  1. nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan]
 [ 7. nan nan nan nan nan  1. nan nan

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 1.  0. nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan  2.]
 [ 3. nan  2. nan nan nan nan nan]
 [ 4. nan nan nan nan  2. nan nan]
 [ 5. nan nan nan nan nan nan  2.]
 [ 6. nan nan nan nan  2. nan nan]
 [ 7. nan nan nan nan  2. nan nan]
 [ 8. nan  1.  1. nan nan nan  2.]
 [ 9. nan nan nan  1. nan nan  2.]
 [10. nan  2. nan nan  2. nan  2.]
 [11. nan nan nan nan nan  2.  1.]
 [12. nan nan nan nan nan nan  2.]
 [13. nan  1. nan nan nan nan nan]
 [14. nan  0. nan nan nan nan nan]
 [15. nan nan nan nan nan nan  2.]
 [16. nan nan nan nan nan nan  2.]
 [17. nan nan  1. nan nan nan nan]
 [18. nan nan nan nan nan nan  2.]
 [19. nan nan nan  1.  0. nan nan]
 [20. nan nan nan nan  1. nan  2.]
 [21. nan nan nan  0.  1. nan  1.]
 [22. nan nan nan nan nan nan  2.]
 [23. nan nan nan nan nan  1.  2.]
 [24. nan nan nan nan  0. nan nan]
 [25. nan nan nan nan nan nan  2.]
 [26. nan nan nan nan  2. nan nan]
 [27. nan nan nan nan nan nan  0.]
 [28. nan nan nan  0

final partition:  [[1, 12, 14, 24, 44, 11, 16, 32, 35], [8, 23, 2, 3, 5, 9, 13, 18, 20, 21, 25, 26, 29, 45], [0, 4, 6, 7, 19, 30, 34, 39, 40, 41, 42, 46, 33, 36], [10, 43], [17, 15, 22, 28, 31, 37, 38]]
groups found =  5


group of leaves investigated:  (1, 2, 3, 5, 7, 8, 9)
[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 1.  0. nan nan nan nan nan nan]
 [ 2. nan nan nan nan  0. nan nan]
 [ 3. nan nan nan nan nan  1.  2.]
 [ 4. nan nan nan nan nan  2. nan]
 [ 5. nan nan nan  2. nan nan nan]
 [ 6. nan nan nan nan nan  1. nan]
 [ 7. nan nan nan nan nan  2. nan]
 [ 8. nan nan nan nan nan  2. nan]
 [ 9. nan nan nan nan nan  2. nan]
 [10. nan  1.  2. nan nan nan nan]
 [11. nan nan nan nan nan  2. nan]
 [12. nan nan nan nan nan  2. nan]
 [13. nan nan nan nan nan  2. nan]
 [14. nan nan nan nan nan  2. nan]
 [15. nan nan nan nan nan  2. nan]
 [16. nan nan nan nan nan  2. nan]
 [17. nan  2. nan nan nan  1. nan]
 [18. nan nan nan nan nan  2. nan]
 [19. nan nan nan  1. nan nan nan]
 [20. nan nan nan  0. na

final partition:  [[6, 11, 13, 18, 21, 23, 2, 3, 7, 15, 16, 22, 35], [19], [1, 10, 14, 20, 26, 27, 30, 34, 9, 12, 24], [5, 25, 29, 31, 32, 36, 28], [8, 33]]
groups found =  5


group of leaves investigated:  (1, 2, 4, 5, 7, 8, 9)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  0. nan nan nan nan  0. nan nan nan]
 [ 2. nan nan nan nan nan nan  2. nan nan]
 [ 3. nan nan nan nan  1.  2. nan nan nan]
 [ 4. nan nan nan nan  2. nan nan nan nan]
 [ 5. nan nan nan nan  1. nan nan nan nan]
 [ 6. nan nan nan  2.  2. nan nan nan nan]
 [ 7. nan  1.  2. nan nan nan nan nan nan]
 [ 8. nan nan nan  2.  2. nan nan nan nan]
 [ 9. nan nan nan nan  2. nan nan nan nan]
 [10. nan nan nan  2.  2. nan nan nan nan]
 [11. nan nan nan nan  2. nan nan nan nan]
 [12. nan nan nan nan  2. nan  2. nan nan]
 [13. nan  2. nan nan  1. nan nan nan nan]
 [14. nan nan nan nan  1. nan nan nan nan]
 [15. nan nan nan nan  0. nan nan nan nan]
 [16. nan nan nan nan nan nan  1. nan nan]
 [17. nan  1.  2. nan  0. nan nan nan n

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 1.  0. nan nan nan nan nan nan nan]
 [ 2. nan nan nan  2. nan  1. nan nan]
 [ 3. nan nan nan nan nan  2. nan nan]
 [ 4. nan nan nan nan nan  1. nan nan]
 [ 5. nan nan nan nan nan  1. nan nan]
 [ 6. nan nan nan nan  2.  2. nan nan]
 [ 7. nan nan nan nan  2.  2. nan nan]
 [ 8. nan nan nan nan nan  2. nan nan]
 [ 9. nan nan  2. nan  2.  2. nan nan]
 [10. nan nan nan nan nan  2. nan nan]
 [11. nan nan nan nan nan  2.  2. nan]
 [12. nan nan nan nan nan  1. nan nan]
 [13. nan  1. nan nan nan nan nan nan]
 [14. nan  0. nan nan nan nan nan nan]
 [15. nan nan nan  1. nan nan nan nan]
 [16. nan nan nan nan nan  1. nan nan]
 [17. nan nan nan nan nan  0. nan nan]
 [18. nan nan nan nan nan  0. nan nan]
 [19. nan nan nan nan nan  1. nan nan]
 [20. nan nan nan nan nan  1.  0. nan]
 [21. nan nan nan nan nan nan nan  2.]
 [22. nan nan nan nan nan  1. nan nan]
 [23. nan nan  2. nan  2.  2. nan nan]
 [24. nan nan nan nan nan  1. nan nan]
 [25. nan nan nan nan nan

final partition:  [[2, 3, 14, 16, 29, 5, 7, 9, 12, 18, 23, 35, 37], [11, 33, 20], [10, 21, 34], [1, 4, 6, 8, 19, 24, 30, 31, 32, 38, 17, 25], [22], [13, 15, 26, 27, 28, 36]]
groups found =  6


in result of postanalysis found opportunity for merge
[2, 3, 14, 16, 29, 5, 7, 9, 12, 18, 23, 35, 37] [22]
final partition:  [[11, 33, 20], [10, 21, 34], [1, 4, 6, 8, 19, 24, 30, 31, 32, 38, 17, 25], [13, 15, 26, 27, 28, 36], [2, 3, 14, 16, 29, 5, 7, 9, 12, 18, 23, 35, 37, 22]]
groups found =  5


group of leaves investigated:  (1, 3, 5, 6, 7, 8, 9)
[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 1.  0. nan nan nan nan nan nan]
 [ 2. nan nan nan nan  0. nan nan]
 [ 3. nan nan  1.  2. nan  2. nan]
 [ 4.  2. nan nan nan nan nan nan]
 [ 5. nan nan  1. nan nan nan nan]
 [ 6. nan nan nan  1. nan nan  2.]
 [ 7. nan nan  2. nan nan nan nan]
 [ 8. nan nan nan  2. nan nan nan]
 [ 9. nan nan  2. nan nan nan nan]
 [10. nan nan nan  2. nan nan nan]
 [11. nan nan nan  2. nan nan nan]
 [12. nan nan  2. nan nan nan nan]

final partition:  [[0, 4, 6, 11, 12, 17, 25, 31, 22, 34], [32, 33, 35], [15, 18, 20, 30, 36, 37], [1, 3, 5, 7, 8, 9, 10, 13, 14, 16, 19, 21, 23, 24, 26, 27, 28, 29]]
groups found =  4


group of leaves investigated:  (2, 3, 4, 5, 6, 7, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 1.  0. nan nan nan nan nan nan nan nan nan nan nan nan]
 [ 2. nan nan nan nan nan nan nan  1. nan nan  0. nan nan]
 [ 3. nan nan nan nan  1. nan nan  0. nan nan nan nan nan]
 [ 4. nan nan  1. nan nan nan nan nan nan nan nan nan nan]
 [ 5. nan nan  0. nan nan nan nan nan nan nan nan nan nan]
 [ 6. nan  2. nan nan nan nan nan nan nan nan nan nan nan]
 [ 7. nan nan nan nan  2. nan nan nan nan nan nan nan nan]
 [ 8. nan nan nan nan nan  2. nan nan nan nan nan nan nan]
 [ 9. nan  1. nan nan  2. nan nan  0.  1. nan  2. nan nan]
 [10. nan  2. nan nan nan  2. nan  1. nan nan nan nan nan]
 [11. nan nan nan nan nan nan nan  0. nan nan nan  0. nan]
 [12. nan nan nan nan nan nan nan nan nan nan nan  0

final partition:  [[18, 20, 15], [21], [26, 28, 31, 29, 30], [2, 4, 10, 11, 12, 19, 23, 25, 27], [8, 13, 16, 22], [1, 3, 6, 9, 14, 17]]
groups found =  6


in result of postanalysis found opportunity for merge
[18, 20, 15] [8, 13, 16, 22]
final partition:  [[21], [26, 28, 31, 29, 30], [2, 4, 10, 11, 12, 19, 23, 25, 27], [1, 3, 6, 9, 14, 17], [18, 20, 15, 8, 13, 16, 22]]
groups found =  5


group of leaves investigated:  (2, 3, 5, 6, 7, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 1.  0. nan nan nan nan nan]
 [ 2. nan nan nan  1. nan nan]
 [ 3. nan nan nan  2. nan nan]
 [ 4. nan nan nan nan  2. nan]
 [ 5. nan nan  1.  2. nan nan]
 [ 6. nan nan  2. nan  2. nan]
 [ 7. nan  2. nan nan nan nan]
 [ 8. nan nan nan nan nan  2.]
 [ 9. nan nan nan nan  2. nan]
 [10. nan nan nan nan  2. nan]
 [11. nan nan  1. nan  2. nan]
 [12. nan nan nan  2.  2.  1.]
 [13. nan nan nan nan  2. nan]
 [14. nan nan nan  1. nan nan]
 [15. nan nan nan  0. nan nan]
 [16.  1. nan nan nan nan nan]
 [17.  0. nan nan nan nan 

final partition:  [[12, 21, 27], [0, 1, 3, 4, 6, 7, 16, 17, 18, 19, 22, 29, 31, 36, 5, 20], [8, 9, 14, 28, 32, 33, 35, 15, 25], [2, 10, 11, 24, 26, 30, 34, 13, 23]]
groups found =  4


group of leaves investigated:  (3, 4, 5, 6, 8, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  0. nan nan nan nan nan nan nan nan]
 [ 2. nan  2. nan nan nan nan nan nan nan]
 [ 3. nan  1. nan  2. nan  1. nan nan nan]
 [ 4. nan nan  1. nan nan nan nan nan  2.]
 [ 5. nan nan nan nan nan  2. nan nan nan]
 [ 6.  2. nan nan  2. nan  2. nan nan nan]
 [ 7.  2. nan nan  2. nan  2.  2.  2.  1.]
 [ 8. nan nan nan nan nan nan nan  2. nan]
 [ 9.  1. nan  0. nan nan nan nan nan nan]
 [10. nan nan nan nan nan  1. nan nan nan]
 [11.  1. nan  0. nan nan nan nan nan  1.]
 [12. nan nan nan nan nan  2. nan nan  2.]
 [13. nan nan nan nan nan  2. nan nan nan]
 [14.  0.  1.  1. nan nan  2.  1.  2.  2.]
 [15. nan nan  0. nan nan nan nan nan  2.]
 [16. nan nan nan  2. nan nan nan nan nan]
 [17.  0. nan nan nan nan nan 

[[ 0.  1.  2.  3.  4.]
 [ 1.  0. nan nan nan]
 [ 2. nan  0. nan nan]
 [ 3. nan nan  2. nan]
 [ 4. nan nan  1.  2.]
 [ 5. nan nan  2. nan]
 [ 6. nan nan  1. nan]
 [ 7. nan nan  1.  2.]
 [ 8. nan nan  2. nan]
 [ 9. nan nan  2. nan]
 [10. nan nan  2. nan]
 [11. nan nan  2. nan]
 [12. nan nan  2. nan]
 [13. nan nan  2. nan]
 [14.  2. nan  2. nan]
 [15. nan nan  2. nan]
 [16. nan nan  2. nan]
 [17. nan nan  1. nan]
 [18. nan nan  2. nan]
 [19.  1. nan nan nan]
 [20.  0. nan nan nan]
 [21. nan nan  1. nan]
 [22. nan nan  1.  2.]
 [23. nan nan  0. nan]
 [24. nan nan  0. nan]
 [25. nan nan  1. nan]
 [26. nan nan  1.  2.]
 [27. nan nan  0. nan]
 [28. nan nan  2. nan]
 [29. nan nan  1. nan]
 [30. nan nan  2. nan]
 [31.  2. nan  2. nan]
 [32. nan nan  1.  2.]
 [33. nan nan  2. nan]
 [34.  2. nan  2. nan]
 [35. nan nan  2. nan]
 [36. nan nan  0.  1.]
 [37. nan nan  2. nan]
 [38. nan nan  0.  2.]
 [39. nan nan  0. nan]
 [40. nan nan  1. nan]
 [41. nan nan  0. nan]
 [42. nan nan  0. nan]
 [43. nan n

final partition:  [[5, 6, 9, 10, 18, 19, 24, 35, 37], [1, 3, 7, 27, 32, 33, 34, 38, 30, 14], [13, 16, 20, 23, 25, 31], [8, 21], [0, 2, 4, 12, 15, 22, 28, 29, 36, 11, 17, 26]]
groups found =  5


group of leaves investigated:  (1, 2, 4, 5, 7, 8, 9, 10)
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 1.  0. nan nan nan nan nan]
 [ 2. nan nan nan nan  2. nan]
 [ 3. nan nan nan  1. nan nan]
 [ 4. nan nan nan  2. nan nan]
 [ 5. nan nan nan  1. nan nan]
 [ 6. nan nan  2.  2. nan nan]
 [ 7. nan  1. nan nan nan nan]
 [ 8. nan nan  2.  2. nan nan]
 [ 9. nan nan nan  2. nan nan]
 [10. nan nan  2.  2. nan nan]
 [11. nan nan nan  2. nan nan]
 [12. nan nan nan  2.  2. nan]
 [13. nan  2. nan  1. nan nan]
 [14. nan nan nan  1. nan nan]
 [15. nan nan nan  0. nan nan]
 [16. nan nan nan nan  1. nan]
 [17. nan  1. nan  0. nan nan]
 [18. nan nan nan  1. nan nan]
 [19. nan  0. nan  1.  0. nan]
 [20. nan nan nan nan nan  2.]
 [21. nan nan nan  2. nan nan]
 [22. nan nan nan  2. nan nan]
 [23. nan nan  2.  2. nan nan]
 [24

final partition:  [[0, 3, 5, 10, 11, 16, 24, 30, 37, 38, 40, 41, 42, 21, 33], [1, 2, 4, 6, 8, 9, 12, 13, 15, 18, 20, 22, 25, 26, 27, 39, 43, 44, 45, 7, 23, 28], [14, 17, 19, 29, 35, 36], [31, 32, 34]]
groups found =  4


group of leaves investigated:  (2, 3, 4, 5, 6, 8, 9, 10)
[[ 0.  1.  2.  3.  4.  5.]
 [ 1.  0. nan nan nan nan]
 [ 2. nan  2. nan nan nan]
 [ 3. nan  1. nan  1. nan]
 [ 4. nan  2. nan nan nan]
 [ 5.  1. nan nan nan  2.]
 [ 6. nan nan nan  2. nan]
 [ 7.  2. nan nan  2. nan]
 [ 8. nan  2. nan nan nan]
 [ 9.  2. nan nan  2. nan]
 [10. nan  2.  2.  2.  1.]
 [11. nan nan nan  2. nan]
 [12.  1. nan nan nan nan]
 [13.  0. nan nan nan nan]
 [14. nan nan nan  1. nan]
 [15.  1. nan nan nan nan]
 [16.  0. nan nan nan  1.]
 [17. nan nan nan  2. nan]
 [18. nan nan nan nan  2.]
 [19. nan nan nan  2. nan]
 [20.  0.  1. nan  2. nan]
 [21.  1. nan  1.  2.  2.]
 [22.  0. nan nan nan  2.]
 [23. nan  2. nan nan nan]
 [24.  0. nan nan nan nan]
 [25. nan nan nan nan  1.]
 [26. nan nan nan  0

final partition:  [[1, 5, 7, 10, 11, 13, 24, 26, 28, 32, 41, 43, 48, 6, 8, 9, 12, 15, 22, 25, 29, 30, 42, 44, 45, 47], [3, 16, 17, 18, 20, 38, 46, 21, 33, 39], [2], [0, 19, 31, 34, 36, 37, 40, 4, 14, 23, 27, 35]]
groups found =  4


group of leaves investigated:  (2, 3, 4, 5, 6, 7, 8, 9, 10)
[[ 0.  1.  2.  3.]
 [ 1.  0. nan nan]
 [ 2. nan  2. nan]
 [ 3. nan  1. nan]
 [ 4. nan  2. nan]
 [ 5. nan  1. nan]
 [ 6.  1. nan nan]
 [ 7.  2. nan nan]
 [ 8. nan  2. nan]
 [ 9.  2. nan nan]
 [10. nan  2. nan]
 [11. nan nan  2.]
 [12. nan  2. nan]
 [13. nan  2. nan]
 [14. nan  2. nan]
 [15.  2.  2.  1.]
 [16. nan  2. nan]
 [17.  1. nan nan]
 [18.  0. nan nan]
 [19. nan  1. nan]
 [20.  1. nan nan]
 [21.  0. nan nan]
 [22.  0.  1. nan]
 [23.  1. nan nan]
 [24.  0. nan nan]
 [25. nan  2. nan]
 [26. nan nan  1.]
 [27. nan  2. nan]
 [28. nan nan  2.]
 [29. nan  2. nan]
 [30. nan  2. nan]
 [31.  1.  2.  2.]
 [32. nan nan  2.]
 [33.  0. nan nan]
 [34.  2. nan nan]
 [35. nan  0. nan]
 [36. nan  0. nan]
 [37

In [5]:
# export in excel 
#dfnumofisg.to_excel('210715_postcode35_ag.xlsx', engine="xlsxwriter", header=False, index=False)
dfnumofisg.to_excel('210827_psy_ag3.xlsx', engine="xlsxwriter", index=False)