In [121]:
'''Analisis of insensitivity groups'''

import re
#import functions_is as fis

import numpy as np
import pandas as pd
#import string

from itertools import product
from itertools import combinations

In [102]:
def listToString(list1):
    return (''.join(map(str, list1)))

def list_getsome(vec, positions):
    list_n = []
    for y in positions:
        list_n.append(vec[y])
    #print("lnf", list_n)
    return(list_n)

In [34]:
dim = 2
lnum = 3

In [145]:
# upper layer iteration
# test if the set of examples can be realised 

#K = [i for i in range(0,2**lnum)]
K = [i%2 for i in range(0,2**lnum)]
print(K)
lenumeration = [i for i in range(1,lnum+1)] 
print(lenumeration)
res = np.zeros(lnum, dtype = int)
# b = np.array((2,2,2)).reshape(3,1)
#print("{:03b}".format(7))

for i in range(1, 2**lnum): 
    # gen data
    tx = "{num:0{field}b}".format(num=i,field=lnum)
    tx = tx.lstrip()
    tx = tx[::-1]
    res_t = [int(i) for i in tx]
    #res = np.vstack((res, np.array(res_t)))
    res = np.vstack((res, res_t))

res = np.hstack((res, np.array(K).reshape(2**lnum,1)))
print(res)
# собрать новый массив из двух частей: 1. столблцы группы неч. 2. столбцы дополнения
# эти два массива объединить в один
# lnumingroup = 2 #len(lst[j])
# # number of leaves in group
# lcombinations = list(combinations(range(1, lnum+1), lnumingroup))



data = pd.read_csv('test_m7.csv', sep=';')
# load data and rewrite 
lnum = data.shape[1]-1
res = np.array(data)
print(res)
# нужно переписать работу со столбцами для любой геометрии таблицы

# нужно организовать перебор групп любой допустимой длинны, для этих данных
lnumingroup = 2 #len(lst[j])
# number of leaves in group
lcombinations = list(combinations(range(1, lnum+1), lnumingroup))
# posible combinatins of groups
print(lcombinations)



for j in range(0, len(lcombinations)):
    # combine all posible tables of K on entered data
    # fill res1 (1. столблцы группы неч.)
    print("group ", j, "analysis")
    res1 = np.array([res[:, lcombinations[j][0]-1]])
    # ini np.array
    for n in range(1, len(lcombinations[j])):
        res1 = np.vstack((res1, res[:, lcombinations[j][n]-1]))
    #print(res1)
    
    reminder = list(set(lenumeration)-set(lcombinations[j])) 
    res2 = np.array([res[:, reminder[0]-1]])
    for n in range(1, lnum-len(lcombinations[j])):
        res2 = np.vstack((res2, res[:, reminder[n]-1]))
    #print(res2)
    res3 = np.vstack((res1, res2))
    res3 = np.vstack((res3, res[:,res.shape[1]-1])).T
    #print(res3)
    
    #ind1 = np.lexsort((res3[:,0], res3[:,1], res3[:,2]))
    ind1 = np.lexsort([res3[:,i] for i in range(res3.shape[1]-1)])
    #print(ind1)
    
    b = np.zeros(lnum+1, dtype = int)
    # для составления таблицы К по групам мне нужет только последний столбец
    # или даже только ind1 - можно сократить этот код
    for i in ind1:
        b = np.vstack((b, res3[i,:]))
    b = b[1:b.shape[0],:]
    #del first row
    print(b)
    
    tbl_k = np.array(b[:,b.shape[1]-1]).reshape(dim**len(lcombinations[j]),dim**len(reminder))
    # create table K from list combinations table and K
    #K = K.T
    print("tbl_k \n", tbl_k)
    # можно реализовать через lcombinations = list(combinations(range(1, lnum+1), lnumingroup))

    # for now it is necessary to analyze whether the given alphabet is enough
    # second way of analisis
    list_ind = [[i for i in range(tbl_k.shape[0])]]
    # range of strings
    
    for r in range(tbl_k.shape[1]):
        # select a column, from back because extend used further
        print("col", r)
        if(len(list_ind) > dim): 
            print("out of scale")
            break
        for z in range(len(list_ind)-1,-1,-1):
            # select a range in list_ind
            if len(list_ind) > 1 and len(list_ind[z]) == 1: continue
                # whant to reduce consideration of one term elements of list_ind
            else:
                ind_t = []
                print("list_ind", list_ind)
                print("z, list_ind[z]", z, list_ind[z])
                for w in range(dim):
                    # search for every simbol in alphabet
                    if np.where(tbl_k[list_ind[z],r] == w)[0].tolist():
                        range_in_range = np.where(tbl_k[list_ind[z],r] == w)[0].tolist()
                        ind_t.append(list_getsome(list_ind[z], range_in_range))
                        #ind_t.append(np.where(tbl_k[:,r] == w)[0].tolist())
                    print("in ", list_getsome(list_ind[z],
                                              np.where(tbl_k[list_ind[z],r] == w)[0].tolist()))
                        # may be reduced; if all values found
                    #print("found group for merge")
                    #print("in", w, ind_t)
                del list_ind[z]
                list_ind.extend(ind_t)
                #list_ind.insert(z, ind_t)
                # need to insert on del place, bacause of for indexing
                if(len(list_ind) > dim): 
                    print("out of scale")
                    break
    print("out", ind_t)
            
    print(list_ind)
                    
# names = []
# for i in range(0,len(lst)):
#     names.append(listToString(lst[i]))
# # columns for perm in list table
# print(names)

#сделай  pd.data.frame со столбцами с этими именами и размещай в них результаты
#print(res)

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]
[1, 2, 3, 4]
[[0 0 0 0 0]
 [1 0 0 0 1]
 [0 1 0 0 0]
 [1 1 0 0 1]
 [0 0 1 0 0]
 [1 0 1 0 1]
 [0 1 1 0 0]
 [1 1 1 0 1]
 [0 0 0 1 0]
 [1 0 0 1 1]
 [0 1 0 1 0]
 [1 1 0 1 1]
 [0 0 1 1 0]
 [1 0 1 1 1]
 [0 1 1 1 0]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [1 0 0 0 1]
 [0 1 0 0 1]
 [1 1 0 0 0]
 [0 0 1 0 0]
 [1 0 1 0 0]
 [0 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 0]
 [1 0 0 1 0]
 [0 1 0 1 0]
 [1 1 0 1 0]
 [0 0 1 1 0]
 [1 0 1 1 0]
 [0 1 1 1 0]
 [1 1 1 1 0]]
[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]
group  0 analysis
[[0 0 0 0 0]
 [1 0 0 0 1]
 [0 1 0 0 1]
 [1 1 0 0 0]
 [0 0 1 0 0]
 [1 0 1 0 0]
 [0 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 0]
 [1 0 0 1 0]
 [0 1 0 1 0]
 [1 1 0 1 0]
 [0 0 1 1 0]
 [1 0 1 1 0]
 [0 1 1 1 0]
 [1 1 1 1 0]]
tbl_k 
 [[0 1 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
col 0
list_ind [[0, 1, 2, 3]]
z, list_ind[z] 0 [0, 1, 2, 3]
in  [0, 1, 2, 3]
in  []
col 1
list_ind [[0, 1, 2, 3]]
z, list_ind[z] 0 [0, 1, 2, 3]
in  [1, 2, 3]
in  [0]
col 2
list_ind [[1, 2, 3]

In [147]:
    # first way of analisis
#     for q in range(0,tbl_k.shape[0]-1):
#         # compare each string with another. If equal then in one group
#         # it is the strait way
#         #print("q",q)
#         for w in range(q+1,tbl_k.shape[0]):
#             #print("w",w)
#             if (tbl_k[q,:] == tbl_k[w,:]).all(): 
#                 print("found group for merge")
#     # найденные группы склеивай и выходи через брейк к следующему q
